### ISSUE TITLE
Product Details Page Attribute Selection Placeholder is not responsive in Mobile View [Screenshot Added]

### ISSUE THREAD

**Issue by shakib04** [bagisto/bagisto#10008]
**Describe the bug**
When visit to product details, is there is a selection of color or other things, placeholder is not responsive to mobile view.

**To Reproduce**
1. Go to a product details where a selection attribute is used 'from customer view'
2. See placeholder, it is not responsive.

**Expected behavior**
Selection Placeholder should be responsive. It creats confusion to customer point of view.

**Screenshots**
![Screenshot from 2024-07-12 22-43-44](https://github.com/user-attachments/assets/3635ba65-e672-40e0-bd05-c6767db3689a)

![image](https://github.com/user-attachments/assets/ea7669c8-1efc-4592-bf51-9caf3ad64e56)

**Smartphone (please complete the following information):**
 - Device: Xiaomi K20 Pro, IPhone XR
 - Browser: Chrome
 - Bagisto Version: 2.1.2

**Comment by ashishkumar-webkul** [comment]
@shakib04 

Thank you so much for your concern and query. Upon checking the issue, this issue has already fixed in the latest version of bagisto. Hence you can check the same with the updated code.

For this issue you can also follow this PR -> https://github.com/bagisto/bagisto/pull/9741

Thank You So Much.
