### ISSUE TITLE
404 when changing language

### ISSUE THREAD

**Issue by onursonmez** [bagisto/bagisto#10247]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

I am on the German page /arctic-touchscreen-winterhandschuhe. When I change the language to English I get a 404 error. Because in English the link address of the product is /arctic-touchscreen-winter-gloves. Is this a bug?

### Preconditions

Version: 2.2.3
Os: Linux
Web Server: Nginx
PHP: 8.1

### Steps to reproduce

How did I get the error?
1. Change the name of a product in English. Example Arctic Touchscreen Winter Gloves and the URL Key would be arctic-touchscreen-winter-gloves.
2. Switch to another language (e.g. German) and change the name of the product. Example Arctic Touchscreen Winterhandschuhe and the URL Key would be arctic-touchscreen-winterhandschuhe.
3. In the frontend go to the English language product /arctic-touchscreen-winter-gloves. Change the language above. You will get a 404 error.

### Expected Result

When I switch to English while on the German page /arctic-touchscreen-winterhandschuhe, I have to switch to the page /arctic-touchscreen-winter-gloves.

### Actual Result

I got 404 error

**Comment by ashishkumar-webkul** [comment]
@onursonmez 

Thank You So much for bringing the concern to light, We really appreciate your efforts and contribution towards bagisto. We have checked and we will be discussing the same with the team and we will work on this accordingly. 

**Video**

https://github.com/user-attachments/assets/fc6395ee-a5f6-48fc-918f-52e1020ce3aa

**Comment by devansh-webkul** [comment]
@ashishkumar-webkul and @amit-webkul,

To ensure that other languages display correctly, it’s important to fill in the details in all required locales, as English is currently set as the fallback. If content is only entered in Arabic, other locales may lack the necessary data, leading to blank pages or 404 errors. Alternatively, if you’d prefer Arabic to be the default, you could consider setting it as the fallback locale.

**Comment by onursonmez** [comment]
This is not a solution. If Arabic is set as the default language, it will give a 404 error when it switches to English. Also, this bug will fill Google Search Console with 404 pages as many as the number of products on the page because there is a link on the product detail page that gets 404.

At least at this stage, instead of the page falling to 404, a redirect can be made to the home page.

**Comment by devansh-webkul** [comment]
Hi @onursonmez,

I noticed that you’re entering data only in Arabic without including it in the English locale. According to the channel configuration, if English is set as the default locale, any fields that are empty and locale-based will be filled with the default locale’s data.

However, since only Arabic data is being entered, and the product is saved without the default channel locale data, this leads to blank values appearing across various areas.

If your main focus is the Arabic locale, you might consider changing the default locale in the channel settings to Arabic. This way, all empty locale-based fields will fall back to the Arabic data, and this should prevent any 404 issues.

Let me know if this doesn’t resolve the issue—I’d be glad to help further.
