### ISSUE TITLE
Site Maintainance Mode -> Message is not saving and also on Maintainance Mode page Go to Home Button is not working.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/bagisto#10252]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

Master

### Issue Description

Site Maintainance Mode -> Message is not saving and also on Maintainance Mode page Go to Home Button is not working.

### Preconditions

1. Admin must be logged in.

### Steps to reproduce

1. Go to Admin -> Settings -> Channels  -> Maintenance Mode -> Add Message -> Save Settings.
2. Now again edit and check the message -> Message is not saved.
3. now go to shop front -> Maintainance Page 503 -> There we can see Go to Home Button.
4. Click on it, it is not working.

### Expected Result

1. Message which is added must be saved.
2. Go to Home button should be working or it should be removed.

### Actual Result

Please check the  video for reference.

**Video**

https://github.com/user-attachments/assets/194b3050-f500-4580-be3c-1631088ad109

**Comment by amit-webkul** [comment]
@ashishkumar-webkul ,

I have checked the same in the 2.2 branch, and the maintenance mode text is saving successfully. And the go to home button is working fine. Because currently we are in maintenance mode, whenever we click on that button, it will redirect to the home page, but due to maintenance mode enabled, it will show you an error page.

[Reference Video](https://webkul.chatwhizz.com/share/view-recording/6728918567225a69d1aa3ac1)
