### ISSUE TITLE
Error right after installation.

### ISSUE THREAD

**Issue by daimalkogaz** [bagisto/bagisto#1388]
After the installation is complete I get redirected to the admin login page which returns this error:
![market_error](https://user-images.githubusercontent.com/52038506/64220489-4655e880-ced2-11e9-97af-3a730d530847.jpg)

Is there an easy fix to this?

**Comment by wasiqaftab** [comment]
do you find any solution for it

**Comment by ilson-nobrega** [comment]
Man, just go to the file: "packages/Webkul/Core/src/Eloquent/Repository.php" and change line 88 (count method) to make it compatible with "vendor\prettus\l5-repository\src\Prettus\Repository\Eloquent\BaseRepository.php" line 346.

**The problem is exactly there, the child class method has the number of different parameters of the parent class.**

Just copy count function from vendor and paste them inside of the core of Webkul.

This is a workaround, but it works!

**Comment by ilson-nobrega** [comment]
@wasiqaftab If you make the change I mentioned above, it will work for you too.

**Comment by wasiqaftab** [comment]
@ilson-nobrega thanks but issue is i have that repository in the following path

**Comment by prashant-webkul** [comment]
@wasiqaftab It was situation mayhem yesterday and its official that all releases except current master will not be installed properly due to dev dependencies present in Bagisto's **composer.json**.

Although this should not hurt as our current master has curbed all the dev dependencies and that can be used in production as well as development.

**Regards**,
Bagisto Team.

**Comment by wasiqaftab** [comment]
@prashant-webkul Thanks yes i try to run master branch it works fine. now the new issue which i see is when we npm install on windows it works fine but when we do npm run dev it gives error or inProduction variable. but i test this on mac its working fine

**Comment by jyoti-webkul** [comment]
- Framework Version: 0.1.6

----------------------------------------
Fixed
