### ISSUE TITLE
How can I add Persian language?

### ISSUE THREAD

**Issue by AGhasemzadeh** [bagisto/bagisto#152]
How can I add Persian language?

**Comment by prashant-webkul** [comment]
1. Goto to settings and add a new Locale for Persian.
2. Goto to Channels and make a new channel or edit the active one, there you have to select Persian in locales and save the or create a new channel with it.
3. See the image below it is a product form.
![cropped](https://user-images.githubusercontent.com/41140572/48928502-a3fde300-ef05-11e8-8819-a1b66237876f.png)
4. Right after where Edit Product's heading there are two select fields the first one is for selecting channel and second one is for selecting Locale.
- The presence of these two fields at the start indicates the values of that or in this case 'Product' is dependent on Channel and Locale both.
5. In the picture above i have marked two things one are Channel and other is Locale which is directly above on the right of field **'Name'**.
- This indicates that the field Name's value is dependent on channel and locale both which provides you to add support for Persian language.
- You have to concern about the values of products and categories because the of both these things are channel and locale dependent both.

Please go on if you have more problems regarding translations.

**Comment by prashant-webkul** [comment]
Please go and reply on the forum thread below for getting more help:

https://forums.bagisto.com/topic/15/language-translations

**Comment by alighasemzadeh** [comment]
@prashant-webkul 
Hello,
I think we need language file to translate it.

**Comment by hChamran** [comment]
@alighasemzadeh 
Hi,
I create fa files for bagisto. you can see at [this ](https://github.com/hChamran/persian-bagisto)page.

**Comment by alighasemzadeh** [comment]
@hChamran 
Hello
We can have bagiato.ir for persian users.

**Comment by hChamran** [comment]
@alighasemzadeh 
Hi,
Yeah sure! 👍

**Comment by alighasemzadeh** [comment]
@hChamran 
Hi,
Please message me in telegram.
AGhasemzadeh is my ID.
