### ISSUE TITLE
The email related activities contains 'Bagisto' hardcorded in various mail templates

### ISSUE THREAD

**Issue by prashant-webkul** [bagisto/bagisto#1614]
# Bug report

### Title
**The email related activities contains 'Bagisto' hardcorded in various mail templates.**

### Issue Description
**Bagisto is hard coded in translation strings of Shop, specifically in page titles and email related strings.**

### Preconditions
**I think this branding issue is right there from the beginning of first Bagisto release.**

    1. v0.1.4.
    2. v0.1.5.
    3. v0.1.6.
    4. v0.1.7.
    5. v0.1.8.

### Steps to reproduce
    **Perform any email related activity such as verification email, email subscription confirmation, etc.**

### Expected result
    **The Bagisto should not come in those mail templates.**

### Actual result
    **Some dynamic variable such as env('APP_NAME') should have been used.**

**Comment by rumansaleem** [comment]
Hey @prashant-webkul! I'd Like to work on it.

**Comment by prashant-webkul** [comment]
> Hey @prashant-webkul! I'd Like to work on it.

Yeah why not this is community, we like to help each other. You also do your part.

Thanks.

**Comment by rumansaleem** [comment]
Currently, on the master branch, I see that `Bagisto` is not hard-coded anywhere in the Shop package.
 
As the issue is labelled for specific versions, I think I need to make changes to every previous release. I am not used to with such workflow, I need a little guidance here. 

It would be great, if you can guide me how to proceed with this.

**Comment by prashant-webkul** [comment]
You just need to PR this fix to current master branch of Bagisto. We do not branch our releases yet.
