### ISSUE TITLE
Password confirmation should ask before deleting any user.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#1648]
# Bug report

### Title
   Password confirmation should ask before deleting any user.
### Issue Description
Password confirmation should ask before deleting any user.
### Preconditions

    1. framework Version- 0.1.8

### Steps to reproduce
  
    1. step1- From setting grid open user
    2. step2-Delete the user

### Expected result
It should ask to enter password before deletion
### Actual result
   User gets deleted without password confirmation
![Screenshot (93)](https://user-images.githubusercontent.com/45203177/66986819-39d1cc00-f0dd-11e9-90b9-d85080e9d9fc.png)

**Comment by ghermans** [comment]
To be honest i don't get the point why a password confirmation would be required for deleting a user?

**Comment by yuvrajsab** [comment]
working on this issue

**Comment by ghermans** [comment]
well i can understand that we would do this in the customer account section.
but when it comes to deleting a user from the backend, then why not simply show a popup: "Are you sure you want to remove this user?" instead of each time asking the password from your account (you can't delete a user without being logged in anyway..)
