### ISSUE TITLE
PWA-Notification permission granted.

### ISSUE THREAD

**Issue by marcelowu** [bagisto/bagisto#2352]
add to home screen not showing android 9,
and how to change  language the PWA.
Thanks!

**Comment by aayush-webkul** [comment]
Hello marcelowu
Just follow these steps in order to remove firebase token error:
1. Go to packages -> Webkul -> PWA -> publishable
2. Now copy firebase-messaging-sw.js file and paste it into "public" folder in the root of your project.

Another thing.
Use chrome or firefox browser for add PWA to your home screen and it will work fine in Android 9 and 10.

**Comment by marcelowu** [comment]
add PWA to home screen start URL is yanz.com.br, not yanz.com.br/mobile

**Comment by aayush-webkul** [comment]
Hello marcelowu
To change the language of PWA:
1. Go to Admin panel -> settings -> Locales.
2. Now from there change the locale or add a new one.
3. Save it and your language of PWA will be changed.

Another things.
1. Please do not change the start URL of Bagisto-PWA as it will also affect the other routes.
2. Make sure that your website is working on https:// with proper ssl certifications in order to use Push Notifications as the firebase API requires https://.
