### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by marcelowu** [bagisto/bagisto#2511]
GET https://bagisto.test/api/checkout/cart 500 (Internal Server Error)
A bad HTTP response code (404) was received when fetching the script.
Uncaught TypeError: messaging.usePublicVapidKey is not a function
 GET https://bagisto.test/api/wishlist/add/1 401 (Unauthorized)
 GET https://bagisto.test/api/checkout/cart 500 (Internal Server Error)

![Capturar](https://user-images.githubusercontent.com/30912144/74864778-d11a8a80-532e-11ea-9bff-79bde28c8df3.PNG)

Thanks!

**Comment by aayush-webkul** [comment]
Hello marcelowu.

Which version of PWA you are using right now ?
What you can do is:

-> Go to packages/Webkul/PWA/publishable/pwa
-> Now copy firebase-messaging-sw.js.
-> Paste it into the public folder present in the root of your project. (bagisto-project/public).
-> Now clear the site data and do a hard reset this error will be gone.

Also I request you to use the latest version of PWA. This problem is fixed in that.
Thanks and Regards
Aayush Bhatt
