### ISSUE TITLE
API checkout/cart returns null for guest user

### ISSUE THREAD

**Issue by merdiano** [bagisto/bagisto#2684]
api/checkout/cart returns {"data":null} for guest user
framework version 0.2

**Comment by rahulshukla-webkul** [comment]
Hi @merdiano 

Can you provide the some information as we are not getting this issue.

**Comment by merdiano** [comment]
i tried to use it as REST api for mobile app. And it returned null

**Comment by Mizan-Rifat** [comment]
@merdiano i have same problem.do you have solution??

**Comment by devansh-webkul** [comment]
Cart giving data null sometimes needs to reproduce that.

**Comment by devansh-webkul** [comment]
After checking and researching this null issue. Cart items are stored in sessions and PHP Sessions uses a cookie to keep track of the session. When the javascript makes requests then it doesn't include cookies because it's a cross-domain request so the session can't be tracked.

That's the reason on the same domain it is working but when doing cross-platform it's not.

If you are hitting the add cart item API, you will get the data with the cart's id. So, you need to save this at the client end or cookies to have track of the cart.

I am concluding that this is not a bug, if someone creating with a frontend framework it should be handled at the frontend as well.
