### ISSUE TITLE
In case of large Content it display outside of the slider.

### ISSUE THREAD

**Issue by Jyoti-Singh1** [bagisto/bagisto#274]
Framework Version: 0.1.2
Add a large content and images on slider content field and see the slider on frontend.
![screenshot 21](https://user-images.githubusercontent.com/45203177/49514576-737d5800-f8ba-11e8-9a1a-3ef8abc2cc70.png)

**Comment by prashant-webkul** [comment]
I think admin will not spoil his slider images by this and there is no way to programmatically check whether the content is too much or not.
It is solely admin's responsibility to maintain the aesthetics of what will be put as the content on the sliders or the storefront.

This issue is getting closed.
