### ISSUE TITLE
how to change checkout proccess

### ISSUE THREAD

**Issue by farshadff** [bagisto/bagisto#2811]
hi , i want to make changes to checkout process and onechange route . so what i want to do is to remove the steps and show them all together because i removed the vuejs from the public side of the site . now i see some routes like :
```
 //Checkout Save Address Form Store
    Route::post('/checkout/save-address', 'Webkul\Shop\Http\Controllers\OnepageController@saveAddress')->name('shop.checkout.save-address');

    //Checkout Save Shipping Address Form Store
    Route::post('/checkout/save-shipping', 'Webkul\Shop\Http\Controllers\OnepageController@saveShipping')->name('shop.checkout.save-shipping');

    //Checkout Save Payment Method Form
    Route::post('/checkout/save-payment', 'Webkul\Shop\Http\Controllers\OnepageController@savePayment')->name('shop.checkout.save-payment');

    //Checkout Save Order
    Route::post('/checkout/save-order', 'Webkul\Shop\Http\Controllers\OnepageController@saveOrder')->name('shop.checkout.save-order');
```
from what i understood is that this vuejs is posting data to other routes before the `save-order` route . so here is my question is there any solution to make all this routes together or make 1 route for all of it as you have some how in this new theme you published . thanks in advance

**Comment by shubhwebkul** [comment]
Hey @farshadff 
In which theme do you want to override checkout process ?

**Comment by rahulcs0082** [comment]
Hi @farshadff 

In the new theme, we have not changed the route, just combine all forms on a single page and when a user places an order then each route is used to call one by one.

You can use the above tactics otherwise you can create a single route for it, which will consist of all this data and when a user places the order, this data will be saved in the database.
but to achieve this, you need to do some changes in shipping and payment method as we get shipping once address gets saved and payment method after the shipping. You need to gets it at the same time on the controller and passed it's to your checkout view.

If you want to change it only to view perspective then use the first way as it is simple and it is already implemented in our new theme.

**Comment by farshadff** [comment]
thats right  true.Thanks for the help <3
