### ISSUE TITLE
Role should we have view permission?

### ISSUE THREAD

**Issue by Mohammedalasaad** [bagisto/bagisto#2864]
Hi,
I can see the role has  "Add Edit Delete" .. I think View permission will be great to have with the list.
so.. Add, Edit, Delete and View.

Regards
<img width="454" alt="Screenshot 2020-04-10 at 14 32 34" src="https://user-images.githubusercontent.com/48674512/78990991-23f70e00-7b38-11ea-97e5-cceb2b5b6ef3.png">

**Comment by rahulcs0082** [comment]
HI @Mohammedalasaad 

We mainly use Datagrid to show all views so if you add any of these permissions (Add, Edit, Delete) , view permission will be automatically given, we don't need to give it separately and none of these actions performed without the view. 

We don't have any separate views for products, categories etc that's why view permission is not there.
