### ISSUE TITLE
Error when creating a category

### ISSUE THREAD

**Issue by manatech** [bagisto/bagisto#2901]
# Bug report

### Title
**SQL Error when creating a category**

### Issue Description
**I am getting an error when I try to create a category.**
`"SQLSTATE[HY000]: General error: 1267 Illegal mix of collations (utf8mb4_unicode_ci,IMPLICIT) and (utf8mb4_general_ci,IMPLICIT) for operation '=' (SQL: update `categories` set `_lft` = case when `_lft` >= 14 then `_lft`+2 else `_lft` end, `_rgt` = case when `_rgt` >= 14 then `_rgt`+2 else `_rgt` end where (`_lft` >= 14 or `_rgt` >= 14))`

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. Running on localhost with xampp
     2. Operating Sytem: Windows 10 pro

**Comment by Mohammedalasaad** [comment]
Did u try to change the collations type for the table so they have the same.
https://stackoverflow.com/questions/1241856/illegal-mix-of-collations-error-in-mysql

**Comment by shivam-webkul** [comment]
Open your phpmyadmin in browser and find your bagisto database then try to run these two queries in db console 

```
1. ALTER TABLE categories CONVERT TO CHARACTER SET utf8;
2. ALTER TABLE category_translations  CONVERT TO CHARACTER SET utf8;
```

**Comment by muokid3** [comment]
works for me @shivam-webkul thanks

**Comment by biru2042** [comment]
I followed instruction you posted @shivam-webkul above but I got error When creating a category on xampp 
SQLSTATE[HY000]: General error: 1449 The user specified as a definer ('merostores'@'localhost') does not exist (SQL: update `categories` set `_lft` = case when `_lft` >= 14 then `_lft`+2 else `_lft` end, `_rgt` = case when `_rgt` >= 14 then `_rgt`+2 else `_rgt` end where (`_lft` >= 14 or `_rgt` >= 14))

**Comment by shivam-webkul** [comment]
Then you need to check the database credential after that try to  run cmd,

**Comment by nickezekias** [comment]
> Open your phpmyadmin in browser and find your bagisto database then try to run these two queries in db console
> 
> ```
> 1. ALTER TABLE categories CONVERT TO CHARACTER SET utf8;
> 2. ALTER TABLE category_translations  CONVERT TO CHARACTER SET utf8;
> ```

I would rather advice to set to utf8mb4, as mysql advices, because utf8 is deprecated and will no longer be used! Also the character set utf8 does not work as normal (it uses 3 bytes in mysql instead of 4, that is why it's aliased utf8mb3), so please use utf8mb4!

Read more from official mysql documentation
https://dev.mysql.com/doc/refman/8.0/en/charset-unicode-utf8.html

As to which collation to use utf8mb4_general_ci or utf8mb4_unicode_ci: you should know there is a difference in performance (speed of query execution) and accuracy (during sorts).
**PS**: During new database creation phpmyadmin uses utf8mb4_general_ci by default!

- For Performance: utf8mb4_general_ci, though the performance is said to be negligible given how servers have fast-cpu nowadays. So use this if you have thousands of rows in your table that undergo intensive queries
- For precision: utf8mb4_unicode_ci, if you handle many locales, with many special characters (this is rare and only in really special cases for special apps, so not very likely in your everyday app), you might wanna use this for more accuracy during sorting.

For speed tests between utf8mb4_general_ci and utf8mb4_unicode_ci, checkout this awesome thread where they do a benchmark to compare query execution speeds:
https://exceptionshub.com/whats-the-difference-between-utf8_general_ci-and-utf8_unicode_ci.html#:~:text=utf8mb4_unicode_ci%20is%20based%20on%20the%20Unicode%20standard%20for,such%20as%20when%20using%20particular%20languages%20or%20characters.

**Comment by vishaldamasiya** [comment]
SQLSTATE[HY000]: General error: 1267 Illegal mix of collations (utf8mb4_unicode_ci,IMPLICIT) and (utf8mb4_general_ci,IMPLICIT) for operation '=' (SQL: update `categories` set `_lft` = case when `_lft` between 15 and 16 then `_lft`-1 when `_lft` between 14 and 16 then `_lft`+2 else `_lft` end, `_rgt` = case when `_rgt` between 15 and 16 then `_rgt`-1 when `_rgt` between 14 and 16 then `_rgt`+2 else `_rgt` end where (`_lft` between 14 and 16 or `_rgt` between 14 and 16))

how to slove
