### ISSUE TITLE
Checkout old theme

### ISSUE THREAD

**Issue by cutemonster** [bagisto/bagisto#2937]
the one page checkout is buggy.
Can you point me on how to install the regular multi step checkout theme?

**Comment by cagartner** [comment]
Hey @cutemonster 
Did you are using the Velocity theme? If yes, try to change to default theme, the Velocity have some bugs in the checkout.

**Comment by cutemonster** [comment]
Thanks, using the default now

**Comment by shubhwebkul** [comment]
What issues you guys are facing in checkout ? could you please mention the issues ?

We'll surely check and resolve those asap.

**Comment by cagartner** [comment]
@shubhwebkul 

We need to trigger a loading icon after selecting an address because when we have integration with some shipping method API, sometimes the API can take some time to respond and the page seems to be frozen during this time.

When you have a customer without address or a guest customer you type an address, the shipping methods are loading fine, but when you change the zip code to another and change the address information the shipping methods are not triggered again.

Another problem is the checkout takes a lot of memory in chrome, sometimes the browser froze and I needed to reload, or test in firefox.

Cheers.

**Comment by shubhwebkul** [comment]
Thanks @cagartner for notifying the problems you are facing, we'll surely update the scenario asap.

Also, that would be a great pleasure to receive any pull request from you guys on these points.

**Comment by vaishaliwebkul** [comment]
@cagartner 
It's implemented now.

Thanks.
