### ISSUE TITLE
How to edit address form?

### ISSUE THREAD

**Issue by zakybaraq** [bagisto/bagisto#3043]
Hello,

I want to edit address form. i don't want  country's table because my app is local scale (which means Indonesian scale) I want to put province, post code, and address, is there any way to edit form? it seems so complex to edit it. thanks. 

version 1.1.2

**Comment by rahulcs0082** [comment]
Hi @zakybaraq 

You can override a view and add or remove any field, please follow this one for same - https://forums.bagisto.com/topic/221/how-to-override-view-file-in-bagisto

Second thing is that there will be validation for the country so just create a hidden field and provide default county code in this field while removing country field otherwise, you need to remove the country's validation from different controllers and validation file.

**Comment by zakybaraq** [comment]
@rahulcs0082 Thanks it works
