### ISSUE TITLE
Inactive inventory source are get select in channel and products

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#3068]
# Bug report

### Title
disable inventory source are get select in channel and products

### Issue Description
disable inventory source are get select in channel and products

### Preconditions

    1. framework Version- master

### Steps to reproduce

    1. step1- create inventory source and keep status as inactive
    2. step2- add products in this inventory

### Expected result
  If the inventory is inactive then it should not be shown while editing product

 If the inventory is inactive then it should also not visible in the channels

### Actual result

>    In actual result, deactivated inventories also working

* [points....]

**Comment by otheriz** [comment]
or you can leave those as it is..

but on the editing product you can add label "......(inactive)" also the total quantity only on active inventory source..better if you can add option at product list "show inactive total quantity" or "show active and inactive total quantity"
for the channels menu..you still show it..but disabled it's option(just add "disabled")..
this is because might be some users need it to put the inactive as a temporary warehouse...

or if you still want to hide the inactive inventory, can you please make the "total quantity" shown on the product list based on the inventory we choose on the channels settings...
and leave a note in the product inventory editing "The total quantity displayed on the product quantity is based on the chosen inventory on channels setting" to avoid the confusion for the new users..

to still achieve the "temporary warehouse" concept.. 

Thank You

**Comment by vaishaliwebkul** [comment]
fixed
