### ISSUE TITLE
Product image is not showing

### ISSUE THREAD

**Issue by vivekshubhu** [bagisto/bagisto#3119]
# Bug report

### Preconditions
**Please provide as detailed information about your environment as possible.**

I have run all these commands below
php artisan cache:clear
php artisan view:clear
php artisan route:clear
php artisan clear-compiled
php artisan config:cache
composer dump-autoload
php artisan vendor:publish
php artisan storage:link

![1](https://user-images.githubusercontent.com/51329802/82823821-f7b90600-9ec7-11ea-8ca2-17e0b78d4b16.PNG)

**Comment by CesarMdz** [comment]
Hello friend, I have the same problem, I even tried to reinstall bagisto from scratch and it keeps giving me the same problem, I hope you can solve it soon, it happened to me in version 1.1.0 and 1.1.2

**Comment by vaishaliwebkul** [comment]
@vivekshubhu @CesarMdz 

Run the following commands from the Bagisto root directory

cd public

unlink storage

cd ..

php artisan storage:link

php artisan config:cache

Thanks

**Comment by vivekshubhu** [comment]
@vaishaliwebkul 
yeah, still got same issue. product folder is created inside the storage, the images are also there but the problem is the src is always like http://localhost:8000/vendor/webkul/ui/assets/images/product/large-product-placeholder.png

**Comment by vaishaliwebkul** [comment]
@vivek-webkul 
could you show the APP_URL in .env file and send the full view screenshot of the storefront along with Request URL.

Thanks

**Comment by vivekshubhu** [comment]
@vaishaliwebkul 
app_url is http://localhost/bagisto/public/
and what is storefront, do u mean front end page?

**Comment by vaishaliwebkul** [comment]
@vivekshubhu 

Yes, share the full view of front end page.

**Comment by vivekshubhu** [comment]
@vaishaliwebkul
 
![screencapture-localhost-8000-2020-05-26-13_33_18](https://user-images.githubusercontent.com/51329802/82874505-c4bd5380-9f55-11ea-98dc-8fd9899a4dfb.png)

**Comment by CesarMdz** [comment]
Hello again, I did the steps you mentioned but the problem was not solved, the same error remains the same.

**Comment by CesarMdz** [comment]
<img src="https://i.ibb.co/NtHmJ5T/Sin-t-tulo.png" alt="Sin-t-tulo" border="0">

**Comment by CesarMdz** [comment]
What I noticed is that in the path: localhost\storage\framework\cache a folder called "data" is not being created, I don't know if it has to see something, I hope and this can help

**Comment by vivekshubhu** [comment]
Hey @vaishaliwebkul if u can help here, I do not know what to do.

**Comment by vivekshubhu** [comment]
@CesarMdz 
Is your problem solved??

**Comment by CesarMdz** [comment]
No friend, I still have the same problem

**Comment by daniel-farina** [comment]
> @vivekshubhu @CesarMdz
> 
> Run the following commands from the Bagisto root directory
> 
> cd public
> 
> unlink storage
> 
> cd ..
> 
> php artisan storage:link
> 
> php artisan config:cache
> 
> Thanks

This solved the issue for me from a clean install on MacOs. I was first getting the syslink error.
First I deleted the public folders from storage/app/public and public/storage, then I ran the storage:link and config:cache commands as posted above.

Thanks

**Comment by vivekshubhu** [comment]
@daniel-farina 
yeah, I run these command many times but sill the images are not showing

**Comment by CesarMdz** [comment]
> php artisan config:cache



> 
> 
> > @vivekshubhu @CesarMdz
> > Run the following commands from the Bagisto root directory
> > cd public
> > unlink storage
> > cd ..
> > php artisan storage:link
> > php artisan config:cache
> > Thanks
> 
> This solved the issue for me from a clean install on MacOs. I was first getting the syslink error.
> First I deleted the public folders from storage/app/public and public/storage, then I ran the storage:link and config:cache commands as posted above.
> 
> Thanks

sorry friend, I just did the steps you told me, first I tried to delete the starage / app / public folder but when doing storage: link it sent me an error because it could not find the folder, so what I did was empty what was inside the public folder (which I think is what you were referring to) but it was not corrected, it continues, I continue with the same error. I followed all the steps and it was not corrected

**Comment by CesarMdz** [comment]
I tried to install bagisto from 0, a clean installation, I tried and I did not, I did the steps they mentioned again and also, I still have the same problem, the images if they are saved because they are in the folder but it does not show them :(

**Comment by CesarMdz** [comment]
@vivekshubhu  hello friend, I think I know what the possible problem may be, check it out and if it is corrected you tell me, apparently you have deactivated a library of php.ini, which is called "Fileinfo", try to activate it and test, I do not have access to php .ini that's why I can't activate it, but try you and tell me how it went

**Comment by CesarMdz** [comment]
> 
> 
> @vivekshubhu hello friend, I think I know what the possible problem may be, check it out and if it is corrected you tell me, apparently you have deactivated a library of php.ini, which is called "Fileinfo", try to activate it and test, I do not have access to php .ini that's why I can't activate it, but try you and tell me how it went

friend, it is solved in my case activating that library "Fileinfo" in the php.ini

**Comment by vivekshubhu** [comment]
@CesarMdz 
hey man, do mean to enable
"extension=fileinfo",
if it is, this already had enabled

**Comment by CesarMdz** [comment]
@vivekshubhu  This worked for me, I did not have that library activated, I do not know if it has to do but I did an installation from scratch as well.

**Comment by farshadff** [comment]
any fix for this ?? when moving image files from one host to another this happens i did all above but still the images wont load they load in admin panel but not front shop

**Comment by vivekshubhu** [comment]
@farshadff 
yeah,
what do you mean moving images from one host to another.
image in admin panel didn't load in my case

![Capture1](https://user-images.githubusercontent.com/51329802/83711623-70942c80-a643-11ea-867b-7e2ea6f8dfc6.PNG)

**Comment by farshadff** [comment]
i did a git reset --hard on server and my images all deleted and then i uploaded the images on server from a backup that i got , i had all the images but its trying to read them from cache i dont know how to cache them or how to copy to the cache directory because the directory does not exist.

**Comment by farshadff** [comment]
i am using v1.1.2 and every thing worked fine until i did a git reset --hard which unfortunately deleted all product images but i had a backup from images then i copied images in product directory but the images wont show up .

the images show in admin panel because its reading from the original directory but not the front side because its reading from a `cache/medium` path ,

i did all the solutions which was on the forums and github issus like :

php artisan cache:clear
php artisan view:clear
php artisan route:clear
php artisan clear-compiled
php artisan config:cache
composer dump-autoload
php artisan vendor:publish
php artisan storage:link

and file_info extension in php and every other thing :) thanks in advance

**Comment by jitendra-webkul** [comment]
I hope above reply fixed your issue, feel free to reopen anytime

**Comment by harmonizerblinks** [comment]
When using Localhost:8000 everything works fyn but when using virtual host or uploaded to a server and map a domain to application, it doesn't show product images.

**Comment by devansh-webkul** [comment]
Hi,

I want to mention that if someone is using the instance just make sure you install the GD extension as mentioned in the docs because in Bagisto we are using the Laravel intervention package which optimizes the image.

Whether you try to optimize, autoload, publish, etc it won't impact unless and until the required dependencies are installed.

https://devdocs.bagisto.com/1.x/introduction/requirements.html#php-extensions

**Comment by harmonizerblinks** [comment]
I'm using https://www.cloudways.com for hosting, everything is already installed.
here is the live site link https://sparkonlineshop.com

**Comment by devansh-webkul** [comment]
Hi @harmonizerblinks,

The images in the mentioned sites are the default placeholder, images are not optimized yet, try this,
https://github.com/bagisto/bagisto/issues/4843#issuecomment-831668608

**Comment by harmonizerblinks** [comment]
the Optimized Images are there but not displaying and the fallback is the placeholder on error.

**Comment by harmonizerblinks** [comment]
Everything works fyn when using Localhost:8000 url. only when it's deployed or using a visual host url locally it doesn't display.

**Comment by devansh-webkul** [comment]
I just checked by uploading an image in your instance. In the admin panel, it's showing an image that means your intervention package is not working.

Please install all dependencies.

And also please use the forum for discussions, don't reply on the closed issues,
https://forums.bagisto.com/

**Comment by csiber** [comment]
I has resolved it by check config of nginx and comment out config lines for cache static files

        #location ~* \.(jpg|jpeg|png|gif|ico|mp3|mp4|mov)$ {
        #       expires 30d;
        #}
Hope it can help other people with this kind of issue.
