### ISSUE TITLE
Horizontal menu instead of vertical menu.

### ISSUE THREAD

**Issue by akshaypitale** [bagisto/bagisto#3128]
Hi,

I want to change vertical category menu to horizontal menu. And want to remove "shop by category"

![image](https://user-images.githubusercontent.com/23078428/83062200-e44e9c00-a07b-11ea-8317-f71076415020.png)

**Comment by shubhwebkul** [comment]
Hello there,

Currently there is no feature to convert vertical into horizontal menu, you need to customize it.
And in order to remove "shop by category" button, you need to change code [here](https://github.com/bagisto/bagisto/blob/master/packages/Webkul/Velocity/src/Resources/views/shop/layouts/master.blade.php#L81)

Let me know if you have any further query.
Thanks!

**Comment by akshaypitale** [comment]
Thanks for the help @shubhwebkul .
