### ISSUE TITLE
mobile menu categories not found problem

### ISSUE THREAD

**Issue by farshadff** [bagisto/bagisto#3147]
hi , on velocity theme when you on mobile menu and browser categories and subcategories it returns 404 not found its even on live demo .

**Comment by vaishaliwebkul** [comment]
@farshadff 
please specify the bagisto version on which you are getting this issue.

Also, once take a pull from the master branch as this issue does not exist in master

![Screenshot](https://user-images.githubusercontent.com/43210406/83375836-d7200d00-a3ed-11ea-954a-e6a62fa2d70e.png)

**Comment by farshadff** [comment]
@vaishaliwebkul the showing is fine but the links are broken . this bug even exits on your live demo on website i mean if you visit the site and go on mobile menu the sub menu links are all broken and 404

**Comment by vaishaliwebkul** [comment]
@farshadff 
Thanks for notifying this.

bagisto demo is currently not updated, it's running on 1.1.0 version and the issue is resolved in master, so you can pull from the master branch then check.

![Screenshot (4)](https://user-images.githubusercontent.com/43210406/83400295-3565e380-a420-11ea-8061-e129a6200e52.png)

**Comment by farshadff** [comment]
@vaishaliwebkul yes right its fixed in new version thanks

**Comment by PanosDoris** [comment]
Ok nice. I have the same problem. In Which files i have to make changes so that subcategories links works on mobile (404 error). When you say master branch-> you mean that i have to download the whole project again... No this is not a solution for me  I allready deploy bagisto to a webserver and i have made several changes. I just need to tell in which files is the issue and how to fix them More simple tell me  which files i have to take from master and replace them to my server....
