### ISSUE TITLE
Trait 'Illuminate\Foundation\Auth\SendsPasswordResetEmails' not found

### ISSUE THREAD

**Issue by ghermans** [bagisto/bagisto#3238]
# Bug report

### Preconditions
**Please provide as detailed information about your environment as possible.**
    1. master branch.

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. Go to the admin interface authentication page
    2. Click on **forgot password**
    3. You will see the error Trait 'Illuminate\Foundation\Auth\SendsPasswordResetEmails' not found

### Actual result
![Screen44Knipsel](https://user-images.githubusercontent.com/1594411/84606428-6b867700-aea6-11ea-8938-649e0d6fc843.JPG)

**Comment by jitendra-webkul** [comment]
In Laravel 7, laravel introduced "laravel/ui" package and they moved some of code from core to "laravel/ui". Now we have added this package to our composer.json file. Please run "composer install" command in order to get this package.

Please check the following file:

https://github.com/bagisto/bagisto/blob/master/composer.json#L34
