### ISSUE TITLE
SQLSTATE[HY000]: General error: 1267 Illegal mix of collations (utf8mb4_unicode_ci,IMPLICIT) and (utf8mb4_general_ci,IMPLICIT) for operation '=' (SQL: update `categories` set `image` = category/3/qJydwPVykL01lUAqSIpf1RM4JgXZx6sv1Jnfpx1K.jpeg, `categories`.`updated_at` = 2020-07-08 15:14:26 where `id` = 3)

### ISSUE THREAD

**Issue by mando0673** [bagisto/bagisto#3448]
can't add categories
please help

**Comment by vaishaliwebkul** [comment]
@mando0673 
Create db with utf8_general_ci collation or follow this one - #2562

**Comment by Mizan-Rifat** [comment]
i've same issue.plz solve this..

**Comment by vaishaliwebkul** [comment]
@Mizan-Rifat 
Kindly Create db with utf8_general_ci collation or follow this one https://github.com/bagisto/bagisto/issues/2562

**Comment by Mizan-Rifat** [comment]
@vaishaliwebkul  i did it.but still have same problem..

**Comment by vaishaliwebkul** [comment]
@Mizan-Rifat 
how did you do this, can you share the screenshot step by step followed by you

**Comment by Mizan-Rifat** [comment]
well now when i created db with utf8_unicode_ci by this command "CREATE DATABASE bagisto CHARACTER SET utf8 COLLATE utf8_unicode_ci;" it's working...

**Comment by mando0673** [comment]
> @Mizan-Rifat
> Kindly Create db with utf8_general_ci collation or follow this one #2562

oke this work, thank you

**Comment by nickezekias** [comment]
I would rather advice to set to utf8mb4, as mysql advices, because utf8 is deprecated and will no longer be used! Also the character set utf8 does not work as normal (it uses 3 bytes in mysql instead of 4, that is why it's aliased utf8mb3), so please use utf8mb4!

Read more from official mysql documentation
https://dev.mysql.com/doc/refman/8.0/en/charset-unicode-utf8.html

As to which collation to use utf8mb4_general_ci or utf8mb4_unicode_ci: you should know there is a difference in performance (speed of query execution) and accuracy (during sorts).
PS: During new database creation phpmyadmin uses utf8mb4_general_ci by default! (While me I generally go with utf8mb4_unicode_ci)

For Performance: utf8mb4_general_ci, though the performance is said to be negligible given how servers have fast-cpu nowadays. So use this if you have thousands of rows in your table that undergo intensive queries
For precision: utf8mb4_unicode_ci, if you handle many locales, with many special characters (this is not so common and only generally in special cases for special apps, so not very likely in your everyday app), you might wanna use this for more accuracy during sorting.
For speed tests between utf8mb4_general_ci and utf8mb4_unicode_ci, checkout this awesome thread where they do a benchmark to compare query execution speeds:
https://exceptionshub.com/whats-the-difference-between-utf8_general_ci-and-utf8_unicode_ci.html#:~:text=utf8mb4_unicode_ci%20is%20based%20on%20the%20Unicode%20standard%20for,such%20as%20when%20using%20particular%20languages%20or%20characters.

**Comment by mikeyapina** [comment]
I have the same error in 1.3.1. I am using this version because of the express drop ship ..

Illuminate \ Database \ QueryException (HY000)
SQLSTATE[HY000]: General error: 1267 Illegal mix of collations (utf8mb4_unicode_ci,IMPLICIT) and (utf8mb4_0900_ai_ci,IMPLICIT) for operation '=' (SQL: update `categories` set `category_icon_path` = velocity/category_icon_path/1/0TlzmJl0aYlWuw30I7BSYFFQyNAk2le4wjw1m08l.png, `categories`.`updated_at` = 2021-12-30 01:38:48 where `id` = 1)
Previous exceptions
SQLSTATE[HY000]: General error: 1267 Illegal mix of collations (utf8mb4_unicode_ci,IMPLICIT) and (utf8mb4_0900_ai_ci,IMPLICIT) for operation '=' (HY000)
SQLSTATE[HY000]: General error: 1267 Illegal mix of collations (utf8mb4_unicode_ci,IMPLICIT) and (utf8mb4_0900_ai_ci,IMPLICIT) for operation '=' (HY000)

**Comment by devansh-webkul** [comment]
Create database with `utf8_unicode_ci` collation.

**Comment by Ekhel** [comment]
Shit... Same Issues....

**Comment by OBWOCHA** [comment]
Follow this link https://www.youtube.com/watch?v=X_S2kT5OFsU&t=304s the explains how to solve the problem
