### ISSUE TITLE
How the Updates released?

### ISSUE THREAD

**Issue by Xoshbin** [bagisto/bagisto#3567]
Hi, I was asking how do you release updates, I'm watching this repository every day an I see pull requests to fix bugs, but I can't see it released. isn't bug fixes supposed to be released as fast as it's fixed?
And yesterday I saw an issue complaining about upgrading to 1.2.2 whereas as I can see the last version of Bagisto is 1.1.2, Am I missing something or the issue was about upgrading to 1.1.2 please?
And about bagisto-standard repository, what's the different with bagisto/bagisto? which one should we use for production please? 
There's some other question's that people may come in mind when trying to use this repo for production. it should be answered somewhere and take more care about the documentation and explain what's different between the two repos and which one should be used for production and how updates are released. you have a great package but you need to write more documentation.
Thanks for the great package

**Comment by ghermans** [comment]
[bagisto/bagisto](https://github.com/bagisto/bagisto) is the correct github repository, there is a master branch here that we use to add bug fixes and new features to the platform.

Only if there is a bug that has a major impact on the platform, we will quickly push a new release with the fix for this bug.

From now on we have two options to upgrade to a new version

1. The one-click installer https://bagisto.com/en/how-to-update-bagisto-with-one-click
2. Or you can do this manually https://devdocs.bagisto.com/upgrade_to_latest_bagisto.html

**Comment by saurav-webkul** [comment]
1. And about bagisto-standard repository, what's the different with bagisto/bagisto? which one should we use for production please?

bagisto-standard is the repo in which one click update feature is added. However it works as same and you will always get the latest stable release from here. You can use this for production

Thank you for your feedback. This One Click Update feature was released recently and hence bagisto-standard repository is added. More details will follow soon. 

For Support or any query, Bagisto offer many channel like **[live chat on website](https://bagisto.com/en/)**, **[Skype](https://join.skype.com/invite/PcxhAmHq0o7C)**, [Forums](https://forums.bagisto.com/) and **[Community Group](https://www.facebook.com/groups/bagisto/)**
