### ISSUE TITLE
Promotion, combine "percentage" & "fixed amount to whole cart" cart rules get wrong discount amount

### ISSUE THREAD

**Issue by otheriz** [bagisto/bagisto#3638]
# Bug report

### Title
Promotion, combine "percentage" & "fixed amount to whole cart" cart rules get wrong discount amount

### Issue Description
I try to create some promotion for some item with different "apply criteria"
1. 10% discount per product
2. 10 fixed amount to whole cart

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. latest pull from master branch
    2. for easy sample you can use bagisto demo from bagisto website

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. delete all available cart(at demo site)
    2. create first cart rule with this condition&action (Picture 1)
    3. create second cart rule with this condition&action (Picture 2)
![image](https://user-images.githubusercontent.com/11325840/89116334-2998ab00-d4bd-11ea-9195-04bf0e93e212.png)
    
![image](https://user-images.githubusercontent.com/11325840/89116349-6a90bf80-d4bd-11ea-82c9-d0d6ef3839e8.png)

### Expected result
**Tell us what should happen.**

*   Discount -20.00

Additional :
How to achieve multiply by X result..?
Ex : customer get discount for each 4 qty...so when customer but 8 Qty it should get the promotion twice(for each 4 pack)

### Actual result

>    Discount -18.00

* [points....]
![image](https://user-images.githubusercontent.com/11325840/89116417-fa366e00-d4bd-11ea-9c90-e931593fd019.png)

**Comment by bhanu-webkul** [comment]
@otheriz   Thanks for informing us 
There is issue in cart rule if admin has used fixed amount to whole cart in action type with some conditions, when customer add that product which matches condition including few more products in cart then its not working properly.

**Comment by bhanu-webkul** [comment]
fixed in master

**Comment by simonedevita** [comment]
Hi, I think that this bug is fixed in a wrong way.
I would like a discount of 5€ applied in the cart when the user checkout an order with a subtotal >30€ only for the first time (if the cart subtotal is greater than 30€, so for example if the first order is 15€ the customer can use this coupon later when he will buy 30€ of cart subtotal).
I try to explain more in details, I created a new cart rule with those settings:
- usage per customer: 1
- condition type: 1 (every condition is true)
- cart|base_sub_total > 30
- action_type: cart_fixed
- end_other_rules: false
- discount_amount: 5

When the conditions are satisfied the discount remove 5 euros for each different product in the cart, so for example if i add 6 products, I have 30 euros of discount in the cart instead of 5€.
If I rollback before the fix #3638 it works fine.
Thank you.

**Comment by bhanu-webkul** [comment]
@otheriz ,   This issue was related to action type - fixed amount to whole cart and as per fixed amount to whole cart 5€ discount will get applied.
when you will select action type -  fixed amount then  discount amount will be 30€(discount amount *number of item)

**Comment by simonedevita** [comment]
As i said before, selected the option "cart_fixed" which correspond to "fixed amount to whole cart" but i get the same behaviour of "by_fixed" which correspond to "fixed amount".
If i restore this file as it was before 12 Aug, it works like a charm.

**Comment by simonedevita** [comment]
Any news on that?

**Comment by bhanu-webkul** [comment]
fixed amount to whole cart is not working properly when there is two different items in cart, in case of 2 qty of same products its working fine.

**Comment by vaishaliwebkul** [comment]
@simonedevita @otheriz 
the reported bug has been fixed, kindly verify with the updated master branch.
![Screenshot_237](https://user-images.githubusercontent.com/43210406/106434413-850d1b00-6497-11eb-8c9a-ccb219c053eb.png)

![Screenshot_236](https://user-images.githubusercontent.com/43210406/106434435-8b9b9280-6497-11eb-83c9-67b03c642c53.png)



Closing this issue if still exist feel free to reopen.
