### ISSUE TITLE
making this package does not combine bootstrap into velocity.js

### ISSUE THREAD

**Issue by farshadff** [bagisto/bagisto#4214]
hi , i am having trouble using the default bootstrap 4 component like collapse and navigation . so what i think that developers made some changed on the code so i want to add the default bootstrap js to the project not combined in app.js so i wanted to know how to remove this version and the the default one .
this is my problem : when i add menu on responsive it opens and close and dont remain open . and accordion just the same open and closes .
```
  <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">

                            <div class="panel panel-default">
                                <div class="panel-heading" role="tab" id="headingOne">
                                    <h4 class="panel-title">
                                        <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                            <i class="more-less glyphicon fs20 glyphicon-plus"></i>
                                            Collapsible Group Item #1
                                        </a>
                                    </h4>
                                </div>
                                <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
                                    <div class="panel-body">
                                        Orders placed from Monday to Friday 16:00 GMT will be processed and shipped the following business day. Orders placed on weekends and public holidays will be processed and shipped two business days later. No deliveries are made on weekends or public holidays.

                                        Standard delivery time: 3-4 Business Days
                                        Express delivery time: 1-2 Business Days

                                        Swarovski is unable to deliver to PO boxes or APO/FPO addresses.

                                        You may return ordered items up to 28 days after their receipt (with the exception of Gift Cards and customised products). Our returns policy covers all items, including those on promotion or sale.
                                    </div>
                                </div>
                            </div>
</div>
```
 thanks in advance

**Comment by devansh-webkul** [comment]
Hi @farshadff,

For `velocity.js` this is the entry point `https://github.com/bagisto/bagisto/blob/master/packages/Webkul/Velocity/src/Resources/assets/js/app.js`. You can do your changes here and compile again. But make sure there are several dependencies that rely on this, making changes can impact your code as well.

Because in `Velocity` in the JS part `Vue.js` is used.

**Comment by farshadff** [comment]
sorry i dont see how `app.js`  handles bootstrap can you tell where can i make changes to bootstrap and make it to default bootstrap because i see for navigation bagisto team made some changes on that . thanks

**Comment by justtake** [comment]
I was similar problem with bootstrap accordion in bagisto 1.3.3. CSS is from bootstrap 4.3.1 but JS is from bootstrap 3.4.1. Accordion based on example from 4.3.1 was not roll up correctly:
![image](https://user-images.githubusercontent.com/7836517/143583917-a23f112f-7ecf-401f-9699-d22eaf6d8269.png)

I found that JS was looking for parent class 'panel' (bootstrap 3.4.1) instead of 'card' (bootstrap 4.3.1):
![image](https://user-images.githubusercontent.com/7836517/143583977-0e46448e-3a1a-4933-956b-73f02b2d2538.png)

Also i have to add some missing css:
`.collapse {
    &.in {
        display: block;
    }
}`

Maby it will helpfull :)
