### ISSUE TITLE
PayPay scripts are being loaded even if inactive

### ISSUE THREAD

**Issue by richmondnursery** [bagisto/bagisto#4248]
# Bug report

### Title
PayPay scripts are loaded via the Smart Button method even if inactive.

### Issue Description
Even if all PayPal related payment methods are inactive, the Smart Button scripts are being loaded into the master template for all pages. This effectively creates POST requests to PayPal enabling their site-tracker.

### Preconditions

    1. 1.2.0
    2. current

### Steps to reproduce
    1. Configure your site with PayPal and PayPal Smart Button set to inactive.
    2. Visit the home page of your site.

### Expected result
There should be no sign of PayPal

### Actual result
The PayPal SDK scripts are being loaded and I see two POST requests being sent to PayPal. This effectively enables their site-tracker features.

The PayPal EventServiceProvider listens for bagisto.shop.layout.body.after event and injects it's code into the master template regardless of being enabled or disabled.

Wrapping the Event::listen directive in an if statement disables the injection. Probably not the ideal solution.
```
if ( core()->getConfigData('sales.paymentmethods.paypal_smart_button.active')) {
  Event::listen('bagisto.shop.layout.body.after', static function (ViewRenderEventManager $viewRenderEventManager) {
    $viewRenderEventManager->addTemplate('paypal::checkout.onepage.paypal-smart-button');          
  );
}
```

**Comment by ariadoos** [comment]
Hi, 
By adding the above-mentioned solution, I ran into the problem  **Getting error Base table channel not found** while uploading my project into dev server and running the composer install command and the same error results for running all the other commands as well. 

I found that I don't have a scheme yet that's why I am getting an error from this EventServiceProvider. So It's better to check the scheme channels as well while registering for this event.


```
if (Schema::hasTable('channels') && core()->getConfigData('sales.paymentmethods.paypal_smart_button.active')) {
    Event::listen('bagisto.shop.layout.body.after', static function(ViewRenderEventManager $viewRenderEventManager) {
        $viewRenderEventManager->addTemplate('paypal::checkout.onepage.paypal-smart-button');
    });
}
```

**Comment by devansh-webkul** [comment]
Hi @ariadoos,

First of all, I want to mention that these changes are already reverted in the latest master. Because one cannot directly access the database in the boot method so in the latest patch we already removed the core config portion.

Because this will create issue at the time of installation.
