### ISSUE TITLE
image search disable functionality is not working

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#4335]
# Bug report

![Screenshot_162](https://user-images.githubusercontent.com/43210406/101037678-5eb72600-35a1-11eb-880a-56b9b6c40421.png)

![Screenshot_163](https://user-images.githubusercontent.com/43210406/101037752-65459d80-35a1-11eb-8c7f-d4c180bb3edf.png)

**Comment by MattWithCurls** [comment]
@vaishaliwebkul :wave: Where exactly is the functionality in bagisto that changes the compare options and wishlist options cause I see in the database that the image search option value is changing.

**Comment by jaseelbavu** [comment]
Hi @vaishaliwebkul,
I have added this functionality. That time it was working and got merged. I'll check what went wrong and revert back to you soon.
Thank you.

**Comment by devansh-webkul** [comment]
Hi @jaseelbavu,

This is because the component will always treat as true because js will always parse it as a string whether you give true or false.

**Comment by jaseelbavu** [comment]
Hi @devansh-webkul 
I have checked the code and came to know that the condition was removed from velocity theme. I tried adding the condition in velocity theme under packages folder and ran php artisan vendor:publish command. But the changes are not reflecting in resources folder. How can i fix that?

**Comment by devansh-webkul** [comment]
Hi @jaseelbavu,

Run with `--force` argument to overwrite the change and i am referencing your changes, the problem lies here,

https://github.com/jaseelbavu/bagisto/blob/f11d75324add9657746c1ff734e7d0959002fac1/packages/Webkul/Velocity/src/Resources/views/shop/UI/particals.blade.php#L356

As blade used inside the string so whether you return true and false it will be treated as a string. So when if the condition is checked it always refers to true.

**Comment by jaseelbavu** [comment]
Hi @devansh-webkul 
I understand your concern and thank you for the info. I have added a fix for both issues.
Thank you.
