### ISSUE TITLE
getting error when setup fresh bagisto from master

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#4413]
# Bug report

- git clone https://github.com/bagisto/bagisto

- cd bagisto

- composer create-project

![Screenshot_181](https://user-images.githubusercontent.com/43210406/103333462-07b74a80-4a94-11eb-8f14-a7fccf6ad676.png)

**Comment by GiovanniMounir** [comment]
Same issue here, seems to be caused by the latest merge [7ea7eadfb6a03dba7481261c82da76f947bbbcee](https://github.com/bagisto/bagisto/commit/7ea7eadfb6a03dba7481261c82da76f947bbbcee) (same error appears in CI output) as I'm able to install when reverting to the previous commit [4f92ca602fc15ffb038dde1db1d153ce90503f4e](https://github.com/bagisto/bagisto/commit/4f92ca602fc15ffb038dde1db1d153ce90503f4e).

**Comment by vaishaliwebkul** [comment]
@GiovanniMounir 
please check now it's working fine with the updated commit.
