### ISSUE TITLE
On product page also price should display according to customer group.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#4478]
# Bug report

### Issue Description
On product page also price should display according to customer group.

### Preconditions
**Please provide as detailed information about your environment as possible.**

    1. framework Version.-1.2.0

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. step1- Set customer group price different than actual product price.
    2. step2- Now check the price of product by logging with that customer group

!
![download - 2021-01-14T141417 408](https://user-images.githubusercontent.com/45203177/104565877-f31da980-5672-11eb-9f5d-a6df5777d10c.png)
![download_-_2021-01-12T200713 954](https://user-images.githubusercontent.com/45203177/104565902-fb75e480-5672-11eb-83f0-1e46064da6a1.png)

**Comment by vaishaliwebkul** [comment]
@jyoti-webkul 
this is already fixed in the master branch, kindly verify with master.

![Screenshot_214](https://user-images.githubusercontent.com/43210406/104587447-f0c84900-568c-11eb-851e-db1c0411ec00.png)

![Screenshot_215](https://user-images.githubusercontent.com/43210406/104587472-f887ed80-568c-11eb-97e5-c4cbfb565ae1.png)
