### ISSUE TITLE
Bagisto Compatibility with PHP 8.0

### ISSUE THREAD

**Issue by vaishaliwebkul** [bagisto/bagisto#4541]
# Bug report

Using composer version 2.0
Using PHP version 8.0

![Screenshot_239](https://user-images.githubusercontent.com/43210406/106559330-42a51600-654b-11eb-9d80-a2fb65276d89.png)

**Comment by devansh-webkul** [comment]
With this one also #4449.

**Comment by ghermans** [comment]
Closed the issue since another issue report already exists since January (#4449).

**Comment by devansh-webkul** [comment]
I am reopening this. The reason is that I have completed the support for Laravel 8 but there are some points that I need to mention.

- Laravel 8 minimum requirement is `PHP 7.3` or up. So I have completed the Laravel 8 support with the existing PHP version.

- Laravel 8 with PHP 8.0, I have checked the `composer.json` dependency. Bagisto relies on some dependency that still doesn't have PHP 8 support. For e.g. `babenkoivan/elastic-scout-driver`, `doctrine/dbal`, and many more which still working on the PHP 8 support. I am regularly checking these dependencies even I have checked with `dev-branch` also. So we need to wait for this.

**Comment by devansh-webkul** [comment]
Milestone to PHP 8 support.

- [ ] Laravel 8 support with existing PHP version i.e. 7.3.
- [ ] Bagisto's Dependency check for PHP 8.
- [ ] Bagisto support for PHP 8.

**Comment by vaishaliwebkul** [comment]
@devansh-webkul 

Framework version: master
PHP Version: 8.0

Getting below error on image search.
when run `php artisan migrate` ->  it says nothing to migrate.



![Screenshot_346](https://user-images.githubusercontent.com/43210406/113742986-c84a6b00-9720-11eb-8fd9-b0c5bf975d5b.png)
