### ISSUE TITLE
500 Internal Server Error on Product Creation

### ISSUE THREAD

**Issue by aayushbhatt18** [bagisto/bagisto#4629]
Bagisto Master Branch

https://user-images.githubusercontent.com/53482391/107918895-83ac1a00-6f90-11eb-80db-09078790ad19.mp4

**Comment by aayush-webkul** [comment]
It specifically shows up when I try to upload a product video.

**Comment by vaishaliwebkul** [comment]
@aayush-webkul 
please increase the upload size in php.ini or upload less than 2MB size of video.
refer to this for more information https://github.com/bagisto/bagisto/issues/4302

**Comment by nikolayandreev** [comment]
@aayushbhatt18 Can you check if your DB collation is utf8mb4_unicode_ci because I had such an issue where if the db collation was not utf8mb4_unicode_ci I got 500 errors thrown in various operations.

To be sure you can try to create a new DB with this collation instead of change the current, because it may not change every table accordingly.
