### ISSUE TITLE
REST API customer authentication require additional steps to work

### ISSUE THREAD

**Issue by nikolayandreev** [bagisto/bagisto#4642]
I am making an integration with the following setup:

Nuxt.js - Front-end framework
Laravel Bagisto - Headless Ecommerce API

Authenticating with @nuxtjs/auth-next plugin doesn't work with the default setup you need to take additional steps in order for it to work, I will explain below the issue and how to solve it, and possibly make a PR I am not sure if you guys edit Laravel base files or just content of package/Webkul

When you login via @nuxtjs/auth plugin you need to hit the `/api/customer/login` endpoint and if it returns success and return the user object, which it does and separates the  token property which is great you consider the user logged in and you use whatever is in data to setUser with it, I prefer to setUser manually because otherwise it's buggy.

Then on page reload, you need to check if the user is loggedIn and hit the `/api/consumer/get` endpoint to get the user object again, this is where the integration was failing, because for some reason it returned 401 Unauthenticated, which is wierd because it's certainly passing Authorization header in the request:
![image](https://user-images.githubusercontent.com/26118671/108072630-cdb7fd00-706f-11eb-8f0d-f00bbc2cd3ab.png)

At first I tought it's a problem with the Accept and Content-Type header, following an old github reply, but Accept header is present and Content-Type cannot be set on an empty GET request, because axios will automatically strip it this was included in PR which I found on axios repo.

So in order to make it work I had to:

**1. Add this lane to app/Http/Kernel.php**
![image](https://user-images.githubusercontent.com/26118671/108072839-11126b80-7070-11eb-8b08-ae004b926a53.png)

**2. Add middleware group to the endpoints which should be accessible only for logged in customers**
![image](https://user-images.githubusercontent.com/26118671/108073110-5898f780-7070-11eb-9649-2eee403c21d9.png)

**3. Run `php artisan jwt:secret`**

Result: 
![image](https://user-images.githubusercontent.com/26118671/108073252-78c8b680-7070-11eb-8881-78676e29ed1a.png)

**Comment by AliRazaLilani** [comment]
follow this [link ](https://devdocs.bagisto.com/1.x/api/getting-started-with-the-api.html#introduction)step by step 
https://devdocs.bagisto.com/1.x/api/getting-started-with-the-api.html#introduction
I think you're missing something.

then run this commands in cmd or bash

```
php artisan cache:clear
php artisan view:clear
php artisan route:clear
php artisan clear-compiled
php artisan config:cache

```

**Comment by nikolayandreev** [comment]
@AliRazaLilani Seems like you're right I need to add `?token=true` at the end of the request like `/api/customer/get?token=true`, but I also need to add it for other endpoints like `GET /api/addresses?token=true` otherwise I get 401 so for anyone struggling with this keep that in mind.

IMHO these are endpoints that guest users shouldn't access anyways, so maybe adding them in the auth.jwt middleware is more elegant solution than adding a query parameter at the end, but since there are many use cases I will close the issue now.

**Comment by AliRazaLilani** [comment]
@nikolayandreev , I'm also working with bagisto APIs and this was something messy to include "token=true" in every request so I have customized it with this and now I don't need to add this param anymore with any request where token is needed.

There are two ways in which you can achieve this 

As there are two totally different sources for api and session( for web users ) so you can emit customers from API controller. 
In every controller you can :
replace this
`$this->guard = request()->has('token') ? 'api' : 'customer';`
with this
`$this->guard = request()->has('token') ? 'api' : 'api';`

**Else**

second option is you can edit query to check if request has authorization rather than request has token param.
For this
replace this
`$this->guard = request()->has('token') ? 'api' : 'customer';`
with this
`$this->guard = empty(request()->bearerToken('Authorization')) ? 'customer' : 'api';`

I've completed app flow from user to paypal and first one is working perfect without adding param. We can omit that condition but still it's good to replace so that we can edit later ( if needed )
