### ISSUE TITLE
Check out page extremely slow

### ISSUE THREAD

**Issue by ImTheRealOne** [bagisto/bagisto#4680]
# Bug report

### Title
Check out page extremely slow

### Issue Description
when checking with route /checkout/cart
It takes more than 80 seconds to generate the checkout page with 12 items in cart.
![image](https://user-images.githubusercontent.com/9104404/108923885-74f7df80-75ee-11eb-816e-a1b9bdafbac3.png)
![image](https://user-images.githubusercontent.com/9104404/108923936-8b9e3680-75ee-11eb-84f4-5ce7d2fa64a6.png)
These sql queries are repeated over thousand times.
### Preconditions

    1. 1.3.0 merge from master branch
### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. add more than 10 items to cart with each items added it becomes slower

**Comment by devansh-webkul** [comment]
Hi @ImTheRealOne,

At checkout page we have not hold any values. We are taking fresh values thats why models loading are too high. But still i am marking this as optimization to see some alternatives and suggestions from the users.

Feel free to contribute. :wink:

**Comment by devansh-webkul** [comment]
I am closing this as the remaining duplicate query is for the cart items only and this can't be possible right now because tax calculations, catalog rules, and cart rules also rely on them.

For making it faster I already suggested changes in the merged PR, developers can plan according to their needs,
https://github.com/bagisto/bagisto/pull/5014#issue-693347059
