### ISSUE TITLE
No option to remove single product from wishlist.

### ISSUE THREAD

**Issue by jyoti-webkul** [bagisto/bagisto#4763]
![download - 2021-03-25T140049 216](https://user-images.githubusercontent.com/45203177/112443074-84e01c00-8d72-11eb-8bb8-68ccf510fba3.png)

**Comment by devansh-webkul** [comment]
Hi @jyoti-webkul,

For removing the product from the wishlist just click the wishlist icon.

**Comment by Ezaldeen99** [comment]
@devansh-webkul  currently in bagisto wishlist API, there is not mention how to remove a specific item from wishlists.  Am I missing something or the documentations need to be updated ?

**Comment by devansh-webkul** [comment]
Hi @Ezaldeen99,

Yes, documentation is missing. I just checked the code resource is available for destroying the wishlist.

~~~php
Route::delete('wishlist/{id}', 'ResourceController@destroy')->defaults('_config', [
    'repository' => 'Webkul\Customer\Repositories\WishlistRepository',
    'resource' => 'Webkul\API\Http\Resources\Customer\Wishlist',
    'authorization_required' => true
]);
~~~

Hope this will help you.

**Comment by Ezaldeen99** [comment]
@devansh-webkul yes I noticed that too, however delete endpoint is not the one which delete item from the wishlists. 

After I tried it yesterday, it seems that sending get request to add endpoint with the product I'd remove the item if it exists and add it otherwise. 


Also I noticed that the configurable products is not being added to the wishlists even after I received that they are successfully added

**Comment by devansh-webkul** [comment]
I will check that and will update when I am working on the docs.
