### ISSUE TITLE
Update Exchange Rates

### ISSUE THREAD

**Issue by aboeldhab74** [bagisto/bagisto#4869]
When I update Exchange Rates this error appears " you have not supplied an api access"

![exchange rate 1](https://user-images.githubusercontent.com/70381640/118363745-2bd47d80-b596-11eb-8040-7172198e5ece.PNG)
![exchange rate 2](https://user-images.githubusercontent.com/70381640/118363746-2d9e4100-b596-11eb-898f-85aa6823abed.PNG)

**Comment by devansh-webkul** [comment]
Hi @vaishaliwebkul and @aboeldhab74,

This is not an issue. The API access key is different for all projects. So this needs to be filled in the `.env` file.

**Comment by devansh-webkul** [comment]
Check this PR, you need to provide this key (FIXER_API_KEY) in the `.env`,
https://github.com/bagisto/bagisto/pull/4874

**Comment by aboeldhab74** [comment]
@devansh-webkul  i created fixer account and get api access key
fixer api key in env file "FIXER_API_KEY"
and the same issue
plz help me

**Comment by devansh-webkul** [comment]
Hi @aboeldhab74,

Are you using master branch or latest version,

Because `FIXER_API_KEY` this added in master version.

Before you need to use  it like this `fixer_api_key=` and after that run `php artisan optimize`.

**Comment by aboeldhab74** [comment]
Hi @vaishaliwebkul 
iam using 1.0 version 
and iam trying with FIXER_API_KEY  and  fixer_api_key
and the same issue 
and when debuging code 
call updateRates function
class Webkul\Core\Helpers\ExchangeExchangeRates

**Comment by devansh-webkul** [comment]
Hi @aboeldhab74,

In version 1.0, use this key,
https://github.com/bagisto/bagisto/blob/3cee45b4a5366f6a6b02146a8ba86770978db1a6/.env.example#L40

And run `php artisan config:cache` or `php artisan optimize`.

Then check.

**Comment by aboeldhab74** [comment]
@vaishaliwebkul 
Sorry
The same Issue

**Comment by devansh-webkul** [comment]
OK, now I am getting this, two exchanges are used.

I will get back to you.

**Comment by devansh-webkul** [comment]
@aboeldhab74,

I just check the code in the master branch, actually, two API exchanges have been configured and the default one has now required the key.

But in your version,
https://github.com/bagisto/bagisto/blob/3cee45b4a5366f6a6b02146a8ba86770978db1a6/config/services.php#L32

Only one exchange is configured so you need to check  this config, whether its matches or not and also then check here,
https://github.com/bagisto/bagisto/blob/3cee45b4a5366f6a6b02146a8ba86770978db1a6/packages/Webkul/Core/src/Helpers/Exchange/FixerExchange.php#L42

I am suggesting you this because you are on the `1.0` version if I am fixing the exchange rate still you need to do some code manually.

**Comment by manirajkatuwal** [comment]
@devansh-webkul  used api key but getting some issue , please hel
![Screenshot (3)](https://user-images.githubusercontent.com/52926387/160239275-e03ec675-4233-4421-b84a-45f65f51031a.png)
p

**Comment by tahiryasin** [comment]
I have provided both api keys in `.env`
```

FIXER_API_KEY=yrNVymqO8by********iXa0nYcrvmk
EXCHANGE_RATES_API_KEY=yrNVymqO8by********iXa0nYcrvmk
```


But still getting the error

![image](https://user-images.githubusercontent.com/2690391/203806262-2409420a-0d42-4216-8228-78a36158edff.png)
