### ISSUE TITLE
url()->to('/') to config('app.url')

### ISSUE THREAD

**Issue by robinflyhigh** [bagisto/bagisto#4914]
When we use Bagisto in load balancer setup and we forward it over the port 80:

url()->to('/') will return HTTP URL instead of HTTPS

config('app.url') will always return HTTPS since it is defined in env.

**Comment by devansh-webkul** [comment]
Hi @robinflyhigh,

This is just a config cache nothing else, I just verified this in master,

With `HTTP`,

![Screenshot from 2021-06-08 12-50-12](https://user-images.githubusercontent.com/68321766/121141029-264a1a80-c858-11eb-9c11-5e58b54874c0.png)

With `HTTPS`,

![Screenshot from 2021-06-08 12-48-36](https://user-images.githubusercontent.com/68321766/121141021-2518ed80-c858-11eb-864a-4ef83c9ea446.png)

**Comment by robinflyhigh** [comment]
This is our Load balancer settings which send the request to port 80: https://i.imgur.com/74bZxK6.png

In the admin panel the submenu is not visible, see https://i.imgur.com/27DPBmR.png

We are using URL::forceScheme('https') in AppServiceProvider.php

**Comment by devansh-webkul** [comment]
This is not an issue, this is just a URL mismatching, and that's why the route name not able to recognize. Just check your settings something is missing.

Try to remove your force scheme and handle your ports redirect via `.htaccess`. So that the app provider won't mess up.

And make sure to clean your caches as well.

**Comment by robinflyhigh** [comment]
Thank you!
