### ISSUE TITLE
SQLSTATE[42000] for type json on old mysql

### ISSUE THREAD

**Issue by rahulanand77** [bagisto/bagisto#4957]
Hi,

When I tried to install Bagisto 1.3.1 on the Hostgator shared hosting, I got an error attached for the "json" type for MySQL while running migrate command. As the majority of the shared hosting companies are using older MySQL versions, they don't support the "json" type. I would request if this issue can be addressed, it would be good. 

The reason is, majority of the people are not using bagisto only due to their shared hosting limitation and forced to use any other framework. Please think about it. 

Thanks

Rahul Anand

**Comment by devansh-webkul** [comment]
Hi @rahulanand77,

If you check the Laravel, Laravel also not made for shared hosting, still, a large audience is trying to do some hack to run it on the shared hosting until this situation is not met.

I also contact many times with many shared hosting but they will not provide any latest support to MySQL and this is the main drawback of shared hosting.

And we have not planned for dropping any support because `json` is used worldwide and has many advantages. All the shared hosting service providers should give this.

I can suggest to you, the Heroku, Digital Ocean Droplets, etc. As they are cheap rates same as shared hosting even you have full control on your instance.

I am closing this and please use the forum for any discussion.

**Comment by ghermans** [comment]
We are also setting up our own multi-region hosting environment to meet the requirements of most users at acceptable prices. more info about this service will become available very soon.
