### ISSUE TITLE
ProductAttributeValue model doesn't contain the database schema for "channel_id"

### ISSUE THREAD

**Issue by Defrothew** [bagisto/bagisto#4985]
# Bug report

### Issue Description
I was reviewing the code for ProductAttributeValue model and I found out that it has an attribute "channel_id" and a relationship to Channel model but upon checking the database migration for product_attribute_values related table modifications, I didn't find any.

### Preconditions
None

#### Bagisto version
- [x] master branch
- [ ] 1.3.1
- [ ] 1.3.0
- [ ] 1.2.0

### Steps to reproduce

https://github.com/bagisto/bagisto/blob/master/packages/Webkul/Product/src/Database/Migrations/2018_07_27_070011_create_product_attribute_values_table.php
https://github.com/bagisto/bagisto/blob/master/packages/Webkul/Product/src/Models/ProductAttributeValue.php

### Expected result
A. Either remove the "channel_id" in $fillable and replace it with "channel" and remove the channel() relationship method in ProductAttributeValue model

B. Add the "channel_id" in database migration for product_attribute_values table

### Actual result
It has the "channel_id" attribute but database schema for it is non-existent

**Comment by devansh-webkul** [comment]
Hi @Defrothew,

Yes, some fixes needed there.

![Selection_001](https://user-images.githubusercontent.com/68321766/123901764-35207a80-d989-11eb-99f2-16a0dca45754.png)

- First, `https://github.com/bagisto/bagisto/blob/8858ed64ffdb07c70652549a8b467b57cf5757eb/packages/Webkul/Product/src/Models/ProductAttributeValue.php#L7` this imported class is not present which causes the error.
- Second due to not having `channel_id` belonging channel not exist.
