### ISSUE TITLE
The product's image should be visible properly in mobile view.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#6276]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Visit the shop on mobile view.
**2.** VIew the products on the home page.

**Actual result:** THe product's image is not showing properly in mobile view. Please find the screenshot [Here](https://prnt.sc/wTKQaOsgr0B5).

**Expected result:** The product's image should be visible properly in mobile view. please take a reference from [here](https://prnt.sc/YtnUzrFNX_TZ).

**Comment by rumensys** [comment]
This is because it's carousel. If you fit images to grid on mobile, as I suggest, you should also change carousel to hard coded grid on homepage. 6 on one row on large screen, 4 on one row on tablet, 4 on two rows on mobile. Same for NEW and FEATURED products. Carousels are loading slow on mobile and only if you begin scrolling down a little.

**Comment by Sanjaybhattwebkul** [comment]
@jitendra-webkul
Now, this issue **is fixed**. so I am **closing** this issue.
And I have attached a screenshot [Here](https://prnt.sc/UiyT1VG73iZO), for future reference.
