### ISSUE TITLE
Discount should be shown only for the product for which we created a catalog rule.

### ISSUE THREAD

**Issue by Sanjaybhattwebkul** [bagisto/bagisto#6406]
**Bagisto Version:** Master

**Steps To reproduce**--

**1.** Log in as an admin.
**2.** Create a configurable product.
**3.** Click on marketing and then catalog rule.
**4.** Create a catalog rule for any one variant of the created configurable product.
**5.** Visit the shop and click on the created product.

**Expected result:** Discount should be shown only for the product for which we created a catalog rule.

**Actual result:** I have created a catalog rule which applies to a single product and discounts the price, but all child products show a slash through the price even though the discount is only set on one product. Please find the screenshot [Here](https://prnt.sc/dWq2T3xTpH1F)

**Comment by papnoisanjeev** [comment]
@Sanjaybhattwebkul 
Please mention the **catalog rule** conditions you have applied or may be the case in which you were facing this issue so that we can reproduce.

After creating a configurable product added a catalog rule condition with product number for main product.
Here is the price for main and child product.

Main configurable product : https://prnt.sc/P8bH07yfL_LO
Variant:  https://prnt.sc/BavPZifhQwrm

**Comment by Sanjaybhattwebkul** [comment]
@papnoisanjeev 
Please follow the given steps properly, then the issue will be reproduced.
