### ISSUE TITLE
when i access the http://localhost/bagisto/public/ i got this issue Undefined variable $__env but every other views are working well

### ISSUE THREAD

**Issue by digitalia24** [bagisto/bagisto#7336]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

latest

### Issue Description

Undefined variable $__env (View: C:\xampp\htdocs\bagisto\public) (View: C:\xampp\htdocs\bagisto\resources\themes\velocity\views\home\index.blade.php)

### Preconditions

xampp local host PHP 8.2.0 laravel 9.52.4

### Expected Result

get my public view

### Actual Result

Undefined variable $__env (View: C:\xampp\htdocs\bagisto\public) (View: C:\xampp\htdocs\bagisto\resources\themes\velocity\views\home\index.blade.php)

**Comment by eartahhj** [comment]
I have started using bagisto just today for the first time, configuring it in my Local environment and I have the same issue.

The other views seems to be working fine, seems like only the homepage has this problem.

I have tried config:cache, cache:clear, and similar things but nothing worked.

Bagisto 1.4.5, PHP 8.1.10, Laravel 9.52.4

**Comment by eartahhj** [comment]
@digitalia24 I think I figured out what the problem was for me, can you verify the same?

Basically, I reinstalled bagisto in another folder with:

`composer create-project bagisto/bagisto`

Here I noticed that there was a message telling me I was missing the PHP extension `sodium`. I don't know if this was the problem but seems that after enabling it, and reinstalling bagisto with the command above, it started working correctly.

So, I stopped my installation, I went to my php.ini and checked I had this enabled:
`extension=sodium`

I enabled it and then I ran again:
`composer create-project bagisto/bagisto`

Since I already had the database configured from before, I just copied the `.env` file I had over the new one.
Otherwise, just modify your .env with database and email settings.

Now, run `php artisan bagisto:install`

It will migrate the database and install the rest.

For me it started working correctly.

Does it work for you too?

**Comment by abdulmalikalomayri** [comment]
@eartahhj  Thank you. Your solution has worked for me. 

The bagisto installation documentation the only required php extstion are:
- php-intl extension
- php-gd extension

but php-sodium extension should be with required too.

**Comment by linux85** [comment]
bonjour je suis nouveau sur laravel et bagisto J'ai suivi toute les étapes de bagisto mais malheureusement la page  d accueil affiche cette erreur
**Undefined variable $__env (View: C:\xampp\htdocs\bagisto\public) (View: C:\xampp\htdocs\bagisto\resources\themes\velocity\views\home\index.blade.php)** 
si quelqu un peut m aider 
merci

**Comment by eartahhj** [comment]
@abdulmalikalomayri good, I think this is linked to jwt since Sodium is about encryption.
I have indeed found this issue that could agree with my hypotesis: [lcobucci/jwt requires sodium](https://github.com/lcobucci/jwt/discussions/741)

@linux85 pouvez-vous essayer d'activer l'extension php "sodium" dans votre php.ini ?
`extension=sodium`
puis réessayez:
`composer create-project bagisto/bagisto`

**Comment by digitalia24** [comment]
> @digitalia24 I think I figured out what the problem was for me, can you verify the same?
> 
> Basically, I reinstalled bagisto in another folder with:
> 
> `composer create-project bagisto/bagisto`
> 
> Here I noticed that there was a message telling me I was missing the PHP extension `sodium`. I don't know if this was the problem but seems that after enabling it, and reinstalling bagisto with the command above, it started working correctly.
> 
> So, I stopped my installation, I went to my php.ini and checked I had this enabled: `extension=sodium`
> 
> I enabled it and then I ran again: `composer create-project bagisto/bagisto`
> 
> Since I already had the database configured from before, I just copied the `.env` file I had over the new one. Otherwise, just modify your .env with database and email settings.
> 
> Now, run `php artisan bagisto:install`
> 
> It will migrate the database and install the rest.
> 
> For me it started working correctly.
> 
> Does it work for you too?

Actually i removed the directory and download the zip file from get and i didn't use 'php artisan bagisto:install' i did all steps manually and it worked for me but i faced another issue product images don't show up

**Comment by eartahhj** [comment]
@digitalia24 did you run `php artisan vendor:publish` ?

**Comment by digitalia24** [comment]
@eartahhj yes i did now it s working fine thank you

**Comment by devansh-webkul** [comment]
Closing this as the user already resolved at its its ends.
