### ISSUE TITLE
Problem in installer reading .env

### ISSUE THREAD

**Issue by robertogallea** [bagisto/bagisto#740]
On a fresh installation under Windows and php 7.3 I get error when running Bagisto. It seems like the installer is not correctly parsing the .env file. Inspecting the code, I found that the problem is **on line 17 of public/installer/install.php**

```php
$data = explode(PHP_EOL,$str);
```

To correct the problem I changed it with the following:

```php
$data = preg_split('/\r\n|\r|\n/', $str);
```

**Comment by prashant-webkul** [comment]
@robertogallea Thanks for giving correction and we are pleased by your response.
In our next update or release there will be several fixes and changes in Bagisto's installer.
And I am confirmed this is also been fixed in that already under the commit of @rahulshukla-webkul https://github.com/rahulshukla-webkul/bagisto/commit/e6ccb45056bff9f803660d766fd12e2c7b4950fe
