### ISSUE TITLE
Changing the translation form to json files

### ISSUE THREAD

**Issue by cagartner** [bagisto/bagisto#774]
Hey guys, I want to discuss a changing on the form that translation was built.

For small projects the default form with the array in PHP files is ok, but for bigger projects, this is a little confusing.

Laravel have the json form file by default too: https://laravel.com/docs/5.8/localization#defining-translation-strings

Section: Using Translation Strings As Keys

What do you guys think?

**Comment by cagartner** [comment]
I'll try to implement when I have time.

More info:
https://laraveldaily.com/laravel-json-based-translations-underscores-__-function/

**Comment by prashant-webkul** [comment]
@cagartner We are having shortage of time due to it we haven't implemented translations in JSON.
So in order to reduce complexity for now we will split our translation files in smaller files such as **auth.php**, **forms.php**, etc.

And surely when the translation will go par beyond to a point when it will create performance issues then we will move to JSON translations.

Thanks.
