### ISSUE TITLE
Zoom box is blurring the product image

### ISSUE THREAD

**Issue by engineer-ashwattha** [bagisto/bagisto#8300]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

1.4.1

### Issue Description

In product detail page when we zoom over the product image, the zoom square box is showing the blurry part of that image. But when we zoom out, the square box looks good but the fonts in the image gets smaller. So,

1. How can we set default zoom in or zoom out so that the portion in the zoomed box doesn't look blurry
2. What should be the ideal size to that even with current default zoom, the image doesn't look blurry

### Preconditions

The product is in our demo server which is a VPS server - Linux based. You can check the actual issue on this webpage: https://www.demo.arkabotanicals.com/arka-adam-plus-?looking_for=International

### Steps to reproduce

1. Check this url: https://www.demo.arkabotanicals.com/arka-adam-plus-?looking_for=International
2. Do the image hover on the product image and you will see the blurry write up in the zoomed box.

### Expected Result

The zoomed box shouldn't show the blurry part. It should be clear.

### Actual Result

The zoomed box is showing the blurry magnified image.

**Comment by Amitk-webkul** [comment]
@engineer-ashwattha 

If you zoom in beyond the original resolution of the image, you will start to see a loss in image quality and potentially encounter blurriness. This is because you are essentially stretching the pixels, which can lead to a decrease in sharpness.

Conversely, if you zoom out from the original image size, you are reducing the number of pixels displayed, which can make the image appear smaller but maintain its clarity.

Therefore, if you want to maintain optimal image quality, it's best to work with the highest-resolution version of the image whenever possible.

**Comment by engineer-ashwattha** [comment]
Hello Amit,

Thank you for the response.

Ofcourse, we are using the high resolution images only. The zoom works when we zoom oout the square box. So, can you tell me from where to set the default zoom option? So, once the page is loaded and a person starts using the magnifying glass, it already shows the zoomed out box.

**Comment by Amitk-webkul** [comment]
@engineer-ashwattha,

To manage the zoom levels you need to follow the below steps.

Go to the path and run the below commands:- 
..packages/Webkul/Velocity

npm install
npm run watch

Reach on [this](packages/Webkul/Velocity/src/Resources/assets/js/UI/components/image-magnifier.vue) path.
