### ISSUE TITLE
mix.version is not appearing via bagisto_asset / js causing caching issues

### ISSUE THREAD

**Issue by caesarcxiv** [bagisto/bagisto#876]
bagisto_asset function needs updated to support below

assets should be called as
{{ asset(mix('vendor/webkul/ui/assets/css/ui.css')) }}

to include versioning

**Comment by devansh-webkul** [comment]
Hi @caesarcxiv,

After checking the whole source code and manifest file. I came to conclusion that this is not a bug.

## Explanation

If you check the 'mix()' method its take two argument first one is the path and the second one is the path of the manifest file. In your case the assets further nested. So you need to proivde the path for manist file as well and this is very important.

### Your case
~~~php
{{ asset(mix('vendor/webkul/ui/assets/css/ui.css')) }}
~~~

### What mix is needed
~~~php
{{ asset(mix('/css/ui.css', 'vendor/webkul/ui/assets')) }}
~~~

Now if you hit die and dump the above thing you will get some string,
![Screenshot](https://user-images.githubusercontent.com/68321766/106438005-e636ed80-649b-11eb-88e1-e7b50d49ffa4.png)

And `bagisto_asset()`method is capable of checking the above string. Just make sure you have registry in `mix-manifest.json`. Because this thing is important.
