### ISSUE TITLE
Custom pages in bagisto not loading css

### ISSUE THREAD

**Issue by darkweb2015** [bagisto/bagisto#888]
There seems to be an issue when creating custom pages in Bagisto.

I followed the instructions laid out here: http://forums.bagisto.com:8080/topic/37/how-to-create-custom-pages

The custom page extends the master layout in the Shop module.  However when trying to view the page, the CSS is not loaded correctly.  It seems to be having an issue not getting the correct bagisto_asset path being returned.

Any ideas on how I can fix this problem?

Thanks

**Comment by rahulshukla-webkul** [comment]
Hi @darkweb2015 

We are basically using theme to show front end & also providing feature to implement own theme also. You can check 'themes.php'  file inside config folder. When you create your own view, then that view actually does not fall under any theme that's why css is not loading properly. So you can create your own       theme or you need to manually use our shop css. Implement Shop css on master like this - <link rel="stylesheet" href="{{ asset('themes/default/assets/css/shop.css') }}"></link>.
