### ISSUE TITLE
After selecting the shipping method change the condition. so input fields are not reset on the cart rule create/edit page. 

### ISSUE THREAD

**Issue by Amitk-webkul** [bagisto/bagisto#8951]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

After selecting the shipping method change the condition. so input fields are not reset on the cart rule create/edit page. 

### Preconditions

1. Admin should be logged in.

### Steps to reproduce

1. Go to 'Admin panel'
2. Click on 'Create cart rule' inside the Promotions/Cart rule
3. Scroll down to 'condition'
4. Add condition as 'shipping method'
5. Now change the condition
6. See the error

### Expected Result

should be reset the input field.

### Actual Result

After selecting the shipping method change the condition. so input fields are not reset on the cart rule create/edit page. [Here](https://prnt.sc/7Q86D0ztwTt8)

**Comment by suraj-webkul** [comment]
Hello, @Amitk-webkul and @ashishkumar-webkul sir.
This is not an issue because when we have selectbox and change it input box by selecting another condtion like price then the previous selected value of selectbox has own value then the input box fill up with that select box value. This will happen when you first select box then change to it from another input field

**Comment by ashishkumar-webkul** [comment]
@suraj-webkul as I understood the concern and found that this is not an issue, hence I am closing the issue.
