### ISSUE TITLE
Support question

### ISSUE THREAD

**Issue by Q-intessence** [bagisto/bagisto#935]
Hi,

This is more of a support question as pose to an issue. 

We are attempting to deploy the this to a shared hosting environment under a subdomain. There are 2 different issues I am experiencing:
.1. Access denied Front end setup:
- Deployed is to a shared hosting is fine
- Running through front end setup I get access denied 
- Error is displaying the web host and not the database host (image
![FrontEnd-Error](https://user-images.githubusercontent.com/581486/58157246-30e8e580-7c78-11e9-8e79-a14f9cad67e2.png)
)
- Double check .env file and DB_HOIST is correct
- Attempted to set details in side the config folder (database.php)
Question: Is the front end view some how doing a local host lookup out side of the general details?

.2. Local setup and deploy
- Setup localhost environment via front end successfully (Site with logo cart promotions,etc displays)
- Manually deployed entire code base and SQL dump in DB host
- Loading front end displays Environment setup page
Question: Assuming every thing has been setup . Is there a way to by pass the Environment setup page? (i.e. is it a config some where I can change)

Thanks in advanced
-Nik-

**Comment by rahulshukla-webkul** [comment]
Hi,

Make sure that details in .env file is correct & if they are correct then you can follow the below step to install it.

1. Install composer if not installed.
2. php artisan migrate
3. php artisan db:seed
4. php artisan vendor:publish
-> Press 0 and then press enter to publish all assets and configurations.
5. php artisan storage:link
6. composer dump-autoload

If following the above step, still you get issues then write us.

Thanks
Rahul Shukla

**Comment by Q-intessence** [comment]
Hi Rahul,
Yes the .env file has the correct DBHOST details
<img width="747" alt="Screen Shot 2019-05-22 at 16 13 18" src="https://user-images.githubusercontent.com/581486/58181774-b1293e00-7cac-11e9-9a73-9f20b4d63cd3.png">

Been digging through the code and there are SQL script in the public folder, which appears to part of the installed. This is a major security risk for SQL injection. So going to revert back to second question: **Assuming every thing has been setup . Is there a way to bypass the Environment setup page? (i.e. is it a config some where I can change) AND **also to remove it from the public folder?****

**Comment by rahulshukla-webkul** [comment]
Hi,

From public folder, delete the folder name called installer & paste the following code in index.php file inside public directory.

<?php

/*
|--------------------------------------------------------------------------
| Register The Auto Loader
|--------------------------------------------------------------------------
|
| Composer provides a convenient, automatically generated class loader for
| our application. We just need to utilize it! We'll simply require it
| into the script here so that we don't have to worry about manual
| loading any of our classes later on. It feels great to relax.
|
*/

require __DIR__.'/../vendor/autoload.php';



/**
 * Laravel - A PHP Framework For Web Artisans
 *
 * @package  Laravel
 * @author   Taylor Otwell <taylor@laravel.com>
 */

define('LARAVEL_START', microtime(true));

/*
|--------------------------------------------------------------------------
| Turn On The Lights
|--------------------------------------------------------------------------
|
| We need to illuminate PHP development, so let us turn on the lights.
| This bootstraps the framework and gets it ready for use, then it
| will load up this application so that we can run it and send
| the responses back to the browser and delight our users.
|
*/

$app = require_once __DIR__.'/../bootstrap/app.php';

/*
|--------------------------------------------------------------------------
| Run The Application
|--------------------------------------------------------------------------
|
| Once we have the application, we can handle the incoming request
| through the kernel, and send the associated response back to
| the client's browser allowing them to enjoy the creative
| and wonderful application we have prepared for them.
|
*/

$kernel = $app->make(Illuminate\Contracts\Http\Kernel::class);

$response = $kernel->handle(
    $request = Illuminate\Http\Request::capture()
);

$response->send();

$kernel->terminate($request, $response);


Thanks
Rahul Shukla
