### ISSUE TITLE
unable to use ProvideDataGridPlus  to implement multidatagrid in bagisto 2.0

### ISSUE THREAD

**Issue by sunarcrajneesh** [bagisto/bagisto#9424]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

master

### Issue Description

While following https://bagisto.com/en/multi-datagrid-ability-in-bagisto/ to create multiple datagrid, we found out that "webcul\ui" is missing.

### Preconditions

 follow https://bagisto.com/en/multi-datagrid-ability-in-bagisto/ to create multiple datagrid.

### Steps to reproduce

 follow https://bagisto.com/en/multi-datagrid-ability-in-bagisto/ to create multiple datagrid.

### Expected Result

Multiple datagrids should be created and package should not be missing.

### Actual Result

The "Webkul\Ui" package seems to be missing.

**Comment by suraj-webkul** [comment]
Hi, [sunarcrajneesh](https://github.com/sunarcrajneesh)

Thank you for bringing this to our attention. We would like to inform you that the "Webkul\UI" package has been intentionally removed in Bagisto version 2.x. We have undergone some restructuring and optimization to enhance the bagisto's performance and maintainability.

If you have any specific concerns or if there are functionalities you are missing due to this removal, please provide more details, and we'll be happy to assist or consider any necessary adjustments.
