### ISSUE TITLE
associate specific products to specific channel

### ISSUE THREAD

**Issue by ghena** [bagisto/bagisto#9437]
### Is your feature request related to a problem? Please describe.

V affected on 2.0
I didnt found a feature able to associate a product to a specific channel.

### Describe the solution you'd like

For example i have 2 channels, and a lot of products.
I would like to assign each channels specifics products to display on the frontend.

### Describe alternatives you've considered

Futher maybe the source inventory  should be linked to a specific channels

**Comment by jitendra-webkul** [comment]
Implemented in [PR #9833](https://github.com/bagisto/bagisto/pull/9833). This implementation will work only with new or fresh databases. Existing databases will continue to function as before, meaning `status` will remain non-channel based because all the product attribute values and the attribute itself are non-channel based.

If you want `status` to be channel-based in the existing database, follow these manual steps:

1. Update the `value_per_channel` column to `1` for the attribute with `id = 7` or `code = status` in the `attributes` table. This step will convert the `status` attribute to be channel-based.
2. Convert the `status` attribute saved in `product_attribute_values` to be channel-based by running the following query on the database:

    ```sql
    UPDATE product_attribute_values
    SET channel = 'default',
        unique_id = CONCAT_WS('|', 'default', locale, product_id, attribute_id)
    WHERE attribute_id = 7;
    ```

Ensure you update your default channel accordingly in the above query.
