### ISSUE TITLE
Can't Checkout

### ISSUE THREAD

**Issue by shaizy1234** [bagisto/bagisto#9501]
### Terms

- [X] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2.1.0

### Issue Description

Can't checkout, even try your online demo its same issue

### Preconditions

I tried also your online demo its same issue, when added product to cart and after adding first address, it did't proceed and give error

### Steps to reproduce

1. Go to 'checkout page'
2. Click on 'checkout'
3. Scroll down to 'it will stop'

### Expected Result

Cannot read properties of undefined (reading 'split')

### Actual Result

Cannot read properties of undefined (reading 'split')

### Screenshots

<img width="1462" alt="Screenshot 2024-02-20 at 20 11 55" src="https://github.com/bagisto/bagisto/assets/160664864/5bf91ef0-f188-43bf-8b45-e973e0cd1ebd">

**Comment by ashishkumar-webkul** [comment]
@shaizy1234 
Thank you so much for the concern. We really appreciate your contirbution for Bagisto.

Checked and Found that this issue is appearing when a guest user is trying to checkout a product, we are fixing this issue.
We will update you when it is done.

**Screenshot**

![Screenshot from 2024-02-21 10-23-58](https://github.com/bagisto/bagisto/assets/92721837/d6b49e82-e9c1-47a8-80d1-32e8c7accc77)

**Comment by jitendra-webkul** [comment]
This fix will be included in today's patch release on GitHub.

**Comment by shaizy1234** [comment]
its been 3 days and I did't see any patch, can you please send patch

**Comment by jitendra-webkul** [comment]
https://github.com/bagisto/bagisto/releases/tag/v2.1.1

**Comment by shaizy1234** [comment]
its not fixed check attached screenshoot on your demo page also.

<img width="1468" alt="Screenshot 2024-02-28 at 21 51 05" src="https://github.com/bagisto/bagisto/assets/160664864/6f7aba6b-d6e7-46ce-a4a8-16bb76ebad13">

**Comment by ashishkumar-webkul** [comment]
@shaizy1234 
We really appreciate your efforts and contribution toward Bagitso.

This issue is appearing when we are using a logged in user and if we have already saved a address for the user and try to checkout with same address then we are facing this issue as in Checkout page addresses, email is a mandatory field.
Hence we are working on it.
We will be updating  you for the same ASAP.

Already raised an issue for the same. Kindly check the issue [here](https://github.com/bagisto/bagisto/issues/9537)

Thank You.

**Comment by ashishkumar-webkul** [comment]
@shaizy1234 

We truly appreciate your efforts and contributions to Bagitso.

This issue arises when a logged-in user attempts to checkout with an address that has already been saved. The problem occurs because the email field is mandatory on the Checkout page. Therefore, we are currently addressing this issue.

Already raised an issue for the same. Kindly check the issue [here](https://github.com/bagisto/bagisto/issues/9537)

Thank You.

**Comment by shivendra-webkul** [comment]
Hi @shaizy1234 We truly appreciate your efforts and contributions to Bagitso. This email  issue is also fixed in master branch
PR link-  https://github.com/bagisto/bagisto/pull/9555

**Comment by jitendra-webkul** [comment]
Fixed in #9547

**Comment by jitendra-webkul** [comment]
Now complete checkout flow has been updated in the following release

https://github.com/bagisto/bagisto/releases/tag/v2.1.2
