### ISSUE TITLE
Product type filter doesn't work when using non-English language

### ISSUE THREAD

**Issue by arne-s** [bagisto/bagisto#9502]
**Describe the bug**
When filtering on "Type" in the admin product overview the _translated_ attribute is used. It should be something like "configurable" or "simple", but instead the translated name is used (in my case "Configureerbaar"), see query below:

select count(*) as aggregate from [...]  and (`product_flat`.`type` = 'Configureerbaar') group by [...] as `aggregate_table`

**To Reproduce**
1. Setup a non English language for the admin (I used 'NL')
2. Go to the product overview in the admin panel:  `/admin/catalog/products`
3. Click the button 'Filter'
4. Select a type from the list (configurable/simple/etc)

**Expected behavior**
It should show the products matching the selected product type (e.g. only configurable products)

**Screenshots**
It doesn't show any products (because it incorrectly used the translated attribute name)

**Desktop (please complete the following information):**
 - OS: macOS 13.5.2
 - Browser: chrome
 - Bagisto version: 2.0.0

**Comment by shivendra-webkul** [comment]
Hi @arne-s 

Thank you for your attention to this matter. I wanted to inform you that the reported issue has already been addressed and fixed in the master branch.

Please proceed to update your local codebase to ensure that you are working with the latest changes and that the issue is resolved on your end as well.

If you have any further questions or encounter any other issues, feel free to reach out. Your cooperation is much appreciated.

Please Check the video:-https://webkul.chatwhizz.com/share/view-recording/65d57866095e2005793d0ab2

**Comment by arne-s** [comment]
thanks, it works now!
