### ISSUE TITLE
Installation failing with postgres

### ISSUE THREAD

**Issue by DrjavaB** [bagisto/bagisto#9783]
### Terms

- [x] Before you openning this issue, i have checked if the issue has already been reported.

### Bagisto Version(s) affected

2.1.2

### Issue Description

  2023_05_26_213105_create_wishlist_items_table ................................. 16ms DONE
  2023_05_26_213120_create_compare_items_table ................................... 9ms DONE
  2023_06_27_163529_rename_product_review_images_to_product_review_attachments .. 17ms DONE
  2023_07_06_140013_add_logo_path_column_to_locales .............................. 1ms FAIL

In Connection.php line 822:
                                                                                            
```
  SQLSTATE[42703]: Undefined column: 7 ERROR:  column "locales/" does not exist             
  LINE 1: update "locales" set "logo_path" = CONCAT("locales/", code, ...                   
                                                    ^ (Connection: pgsql, SQL: update "loc  
  ales" set "logo_path" = CONCAT("locales/", code, ".png") where "logo_path" is null)   
```    
                                                                                            

In Connection.php line 605:
                                                                                 
```
  SQLSTATE[42703]: Undefined column: 7 ERROR:  column "locales/" does not exist  
  LINE 1: update "locales" set "logo_path" = CONCAT("locales/", code, ...        
    
```                                                ^                            
                                                                                 



### Preconditions

fresh postgres installation and bagiso latest version.
installation process using cli (`php artisan migrate`) not gui

**Comment by rahulthomasdev** [comment]
Same issue here. The main problem is in the migration and seed files as it toilered to work with mysql it seems and not with psql, from few errors i confirmed that we need to modify each to work with psql. Now talking about this specific issue, change the line in C:\Users\ASUS\Documents\Workspace\bagista\bagisto\packages\Webkul\Core\src\Database\Migrations\2023_07_06_140013_add_logo_path_column_to_locales.php to ` 
        DB::table('locales')->whereNull('logo_path')->update(['logo_path' => DB::raw('CONCAT(\'locales/\', code, \'.png\')')]);`

**Comment by rahulthomasdev** [comment]
I'm encountering difficulties with other migrations too. It seems like the codebase is heavily dependent on SQL/MySQL.

**Comment by devansh-webkul** [comment]
In initial phase our migration files are highly dependent on the mysql files and however postgress is also in our roadmap but this feature is quite time consuming because we need to plan it for existing as well as new users.

**Comment by Muetze42** [comment]
I attempted to run Bagisto with PostgreSQL and found that even the initial installation (seeders/migrations) fails out of the box. I've documented and fixed the issues I encountered below. 

Note: I only verified the installation process. I haven't tested the application itself. Given the number of MySQL-specific assumptions already present in the seeders alone, I'd expect further incompatibilities throughout the application code.

It's puzzling why Laravel's built-in database-agnostic methods like `Schema::disableForeignKeyConstraints()` were not used, given that they have been available for years and exist precisely for this purpose.

# PostgreSQL Compatibility Fixes

Bagisto ships with several MySQL-specific SQL statements that break on PostgreSQL. This document describes the applied fixes.

## 1. String Concatenation in Migration

**File:** `packages/Webkul/Core/src/Database/Migrations/2023_07_06_140013_add_logo_path_column_to_locales.php`

**Problem:** The migration uses `CONCAT()` with double-quoted string literals:

```php
DB::raw('CONCAT("locales/", code, ".png")')
```

PostgreSQL interprets double quotes as column identifiers, so `"locales/"` is treated as a column name rather than a string value, resulting in:

```
SQLSTATE[42703]: Undefined column: 7 ERROR: column "locales/" doesn`t exist
```

**Fix:** Replace `CONCAT()` with the SQL-standard concatenation operator `||` and single-quoted string literals:

```php
DB::raw("'locales/' || code || '.png'")
```

The `||` operator is supported by PostgreSQL, SQLite, and MySQL (8.0+).

---

## 2. Foreign Key Checks in Seeders

**Files:**
- `packages/Webkul/Installer/src/Database/Seeders/Attribute/AttributeFamilyTableSeeder.php`
- `packages/Webkul/Installer/src/Database/Seeders/Attribute/AttributeGroupTableSeeder.php`

**Problem:** Both seeders use raw MySQL-specific statements to toggle foreign key checks:

```php
DB::statement('SET FOREIGN_KEY_CHECKS=0;');
// ...
DB::statement('SET FOREIGN_KEY_CHECKS=1;');
```

PostgreSQL doesn't recognize `FOREIGN_KEY_CHECKS`, resulting in:

```
SQLSTATE[42704]: Undefined object: 7 ERROR: unrecognized configuration parameter "foreign_key_checks"
```

**Fix:** Replace with Laravel's database-agnostic `Schema` methods:

```php
use Illuminate\Support\Facades\Schema;

Schema::disableForeignKeyConstraints();
// ...
Schema::enableForeignKeyConstraints();
```

Laravel translates these calls to the correct SQL for each driver:

| Driver     | Disable                                    | Enable                                    |
|------------|--------------------------------------------|-------------------------------------------|
| MySQL      | `SET FOREIGN_KEY_CHECKS=0`                 | `SET FOREIGN_KEY_CHECKS=1`                |
| PostgreSQL | `SET session_replication_role = 'replica'` | `SET session_replication_role = 'origin'` |
| SQLite     | `PRAGMA foreign_keys = OFF`                | `PRAGMA foreign_keys = ON`                |

**Important caveat:** On PostgreSQL, `session_replication_role = 'replica'` only disables trigger-based constraints. Regular foreign key checks on `INSERT` statements are still enforced. This means that unlike MySQL, simply disabling foreign key constraints doesn't allow inserting rows that reference non-existent parent records. The seeder execution order must be correct regardless (see fix 3 below).

---

## 3. Seeder Execution Order

**File:** `packages/Webkul/Installer/src/Database/Seeders/Attribute/DatabaseSeeder.php`

**Problem:** `AttributeGroupTableSeeder` ran before `AttributeTableSeeder`. The `attribute_group_mappings` table has a foreign key on `attribute_id`, so inserting mappings before the referenced attributes exist causes:

```
SQLSTATE[23503]: Foreign key violation: 7 ERROR: insert or update on table "attribute_group_mappings"
violates foreign key constraint "attribute_group_mappings_attribute_id_foreign"
DETAIL: Key (attribute_id)=(27) is not present in table "attributes".
```

On MySQL this was masked by `SET FOREIGN_KEY_CHECKS=0`, which fully disables constraint enforcement. On PostgreSQL, constraints are still checked (see fix 2).

**Fix:** Reorder the seeder calls so that parent tables are populated before dependent tables:

```php
// Before (broken on PostgreSQL)
$this->call(AttributeFamilyTableSeeder::class, ...);
$this->call(AttributeGroupTableSeeder::class, ...);  // inserts mappings referencing attributes
$this->call(AttributeTableSeeder::class, ...);        // attributes don't exist yet
$this->call(AttributeOptionTableSeeder::class, ...);

// After (correct order)
$this->call(AttributeFamilyTableSeeder::class, ...);
$this->call(AttributeTableSeeder::class, ...);        // attributes exist first
$this->call(AttributeOptionTableSeeder::class, ...);
$this->call(AttributeGroupTableSeeder::class, ...);   // mappings can now reference attributes
```

---

## 4. Missing NOT NULL Column in Category Seeder

**File:** `packages/Webkul/Installer/src/Database/Seeders/Category/CategoryTableSeeder.php`

**Problem:** The insert into `category_translations` omits the `url_path` column, which has a `NOT NULL` constraint. MySQL implicitly uses an empty string as the default for missing `VARCHAR` columns in strict mode off, but PostgreSQL always enforces `NOT NULL`:

```
SQLSTATE[23502]: Not null violation: 7 ERROR: null value in column "url_path" of relation
"category_translations" violates not-null constraint
```

**Fix:** Explicitly include `url_path` with an empty string in the insert data:

```php
// Added to the category_translations insert
'url_path' => '',
```

---

## 5. Top-Level Seeder Execution Order

**File:** `packages/Webkul/Installer/src/Database/Seeders/DatabaseSeeder.php`

**Problem:** `CoreSeeder` (which seeds channels and `channel_inventory_sources`) ran before `InventorySeeder` (which seeds `inventory_sources`). The `channel_inventory_sources` table has a foreign key on `inventory_source_id`, causing:

```
SQLSTATE[23503]: Foreign key violation: 7 ERROR: insert or update on table "channel_inventory_sources"
violates foreign key constraint "channel_inventory_sources_inventory_source_id_foreign"
DETAIL: Key (inventory_source_id)=(1) is not present in table "inventory_sources".
```

**Fix:** Move `InventorySeeder` before `CoreSeeder`:

```php
// Before (broken on PostgreSQL)
$this->call(AttributeSeeder::class, ...);
$this->call(CategorySeeder::class, ...);
$this->call(CoreSeeder::class, ...);        // references inventory_sources
// ...
$this->call(InventorySeeder::class, ...);   // inventory_sources don't exist yet

// After (correct order)
$this->call(AttributeSeeder::class, ...);
$this->call(CategorySeeder::class, ...);
$this->call(InventorySeeder::class, ...);   // inventory_sources exist first
$this->call(CoreSeeder::class, ...);        // can now reference them
```

---

## 6. Auto-Increment Sequence Not Updated After Explicit ID Inserts

**File:** `packages/Webkul/Installer/src/Database/Seeders/Core/ConfigTableSeeder.php`

**Problem:** `ConfigTableSeeder` inserts 15 rows into `core_config` with explicit `id` values (1-15). In PostgreSQL, inserting with explicit IDs doesn't advance the underlying sequence (`core_config_id_seq`). When `CustomerSocialAccountTableSeeder` later inserts rows without explicit IDs, the sequence generates `id=1` again, causing:

```
SQLSTATE[23505]: Unique violation: 7 ERROR: duplicate key value violates unique constraint "core_config_pkey"
DETAIL: Key (id)=(1) already exists.
```

MySQL's `AUTO_INCREMENT` automatically adjusts to the highest inserted value, so this never surfaces there.

**Fix:** Reset the PostgreSQL sequence after the explicit inserts:

```php
if (DB::connection()->getDriverName() === 'pgsql') {
    $max = DB::table('core_config')->max('id') ?? 0;
    DB::statement("SELECT setval('core_config_id_seq', {$max})");
}
```

This sets the sequence to the current maximum `id`, so the next auto-generated value will be `max + 1`.

**Comment by heiwen** [comment]
@devansh-webkul wondering whether PostgreSQL support still on your roadmap? (we are trying to run Bagisto on Supabase)

**Comment by devansh-webkul** [comment]
Yes, it is already supported in the master branch, and we are planning to release v2.5 by September 15th. If everything goes well, we may release it earlier as well.

**Comment by heiwen** [comment]
Happy to help stabilizing it, is there any beta release planned?
