### ISSUE TITLE
shipping and payment cannot be automatically checked

### ISSUE THREAD

**Issue by chakson** [bagisto/bagisto#9851]
### Is your feature request related to a problem? Please describe.

bagisto 2.1.2
On the checkout page, when placing an order, shipping and payment cannot be automatically checked.
I need to select the shipping method first before the payment method will appear.
![image](https://github.com/bagisto/bagisto/assets/13362753/860c98a9-872a-4d39-ad64-20d2426042e3)

### Describe the solution you'd like

On the checkout page, when placing an order, shipping and payment are automatically checked. This reduces the customer's frequent operations.

**Comment by ashishkumar-webkul** [comment]
@chakson 

Thank you so much for your contribution to Bagisto.

Regarding your concern, I have checked the master branch code and observed that the shipping methods and payment methods are not selected automatically.

Please let me know if I am correct. If not, kindly clarify your concern so that we can assist you further in resolving it.

You can check the video for reference.


https://github.com/bagisto/bagisto/assets/92721837/fbf561f3-ea18-41df-ba20-fab5d7aad9de

**Comment by chakson** [comment]
@ashishkumar-webkul 
Hello, thank you for your reply. What I put forward is not a bug, but the function I want. For example, when there are multiple shipping methods, it can choose the first one by default without the need to choose manually. In the same way, when there are multiple payment methods, select the first one by default

**Comment by ashishkumar-webkul** [comment]
@chakson 

We completely understand your concern and would like to explain why we do not automatically select the payment and shipping methods by default.

It is up to the user to select their preferred payment and shipping methods.
There are many payment and shipping methods available in the module to cater to customer preferences.
In the case of payment methods like PayPal Standard, the user is usually redirected to a separate page, and only then is the order placed. And in this case we will  not be able to understand which shipping method was selected.
For these reasons, we do not provide pre-selected payment and shipping methods.

Hence I am closing this.

I hope this explanation clarifies your concern.

Thank You So Much.
